USE HSDZ_MES;
SET NOCOUNT ON;
DELETE FROM yj_message WHERE 消息码 IN ('TERM_REQUESTED','TERM_TO_ADMIN','TERM_APPROVED','TERM_REJECTED') AND 单据编号 IS NOT NULL;
SELECT COUNT(*) AS term_msgs_left FROM yj_message WHERE 消息码 LIKE 'TERM_%';
