import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeSet;

/** Dump entire HSDZ_MES (all tables DDL+DML, all views DDL) to db/HSDZ_MES-full.sql */
public class _DumpAll {
    static final String URL = "jdbc:sqlserver://localhost:1433;databaseName=HSDZ_MES;encrypt=false;trustServerCertificate=true;loginTimeout=10";
    static final String USER = "yinjia";
    static final String PASS = "Yinjia@2026";
    static final String OUT = "C:/INCER/YINJIA-MES/db/HSDZ_MES-full.sql";

    public static void main(String[] args) throws Exception {
        TreeSet<String> skip = new TreeSet<>(List.of("t1", "t2", "dtproperties"));
        try (Connection c = DriverManager.getConnection(URL, USER, PASS)) {
            TreeSet<String> tables = names(c, "SELECT name FROM sys.tables");
            TreeSet<String> views = names(c, "SELECT name FROM sys.views");
            tables.removeAll(skip);
            System.out.println("tables=" + tables.size() + " views=" + views.size());
            StringBuilder sb = new StringBuilder();
            sb.append("-- HSDZ_MES FULL DUMP (YINJIA-MES) - generated by tools/_DumpAll.java\n");
            sb.append("SET NOCOUNT ON;\n");
            for (String t : tables) {
                String ddl = genTable(c, t);
                if (ddl == null) { System.out.println("[WARN] skip " + t); continue; }
                sb.append(ddl).append("\nGO\n");
            }
            for (String v : views) {
                sb.append(viewDdl(c, v)).append("\nGO\n");
            }
            Files.write(Path.of(OUT), sb.toString().getBytes(StandardCharsets.UTF_8));
            System.out.println("written " + OUT + " bytes=" + sb.length() + " MB=" + (sb.length() / 1048576.0));
        }
    }

    static TreeSet<String> names(Connection c, String sql) throws Exception {
        TreeSet<String> out = new TreeSet<>();
        try (Statement s = c.createStatement(); ResultSet rs = s.executeQuery(sql)) {
            while (rs.next()) out.add(rs.getString(1));
        }
        return out;
    }

    static List<String[]> columns(Connection c, String table) throws Exception {
        List<String[]> cols = new ArrayList<>();
        String sql = "SELECT c.name, ty.name AS typ, c.max_length, c.precision, c.scale, c.is_nullable, c.is_identity, "
                + "c.is_computed, dc.definition AS def FROM sys.columns c "
                + "JOIN sys.types ty ON ty.user_type_id = c.user_type_id "
                + "LEFT JOIN sys.default_constraints dc ON dc.parent_object_id = c.object_id AND dc.parent_column_id = c.column_id "
                + "WHERE c.object_id = OBJECT_ID(?) ORDER BY c.column_id";
        try (PreparedStatement ps = c.prepareStatement(sql)) {
            ps.setString(1, table);
            try (ResultSet rs = ps.executeQuery()) {
                while (rs.next()) {
                    cols.add(new String[] { rs.getString("name"), rs.getString("typ"),
                            String.valueOf(rs.getInt("max_length")), String.valueOf(rs.getInt("precision")),
                            String.valueOf(rs.getInt("scale")), rs.getBoolean("is_nullable") ? "1" : "0",
                            rs.getBoolean("is_identity") ? "1" : "0", rs.getBoolean("is_computed") ? "1" : "0",
                            rs.getString("def") });
                }
            }
        }
        return cols;
    }

    static String colType(String typ, String maxLen, String prec, String scale) {
        switch (typ) {
            case "nvarchar": case "nchar":
                return typ + (maxLen.equals("-1") ? "(max)" : "(" + (Integer.parseInt(maxLen) / 2) + ")");
            case "varchar": case "char": case "varbinary": case "binary":
                return typ + (maxLen.equals("-1") ? "(max)" : "(" + maxLen + ")");
            case "decimal": case "numeric":
                return typ + "(" + prec + "," + scale + ")";
            case "text": case "ntext": case "image": case "xml":
                return typ;
            default:
                return typ;
        }
    }

    static String genTable(Connection c, String table) throws Exception {
        List<String[]> cols = columns(c, table);
        StringBuilder ddl = new StringBuilder();
        ddl.append("IF OBJECT_ID('dbo.").append(table).append("','U') IS NULL CREATE TABLE dbo.[")
                .append(table).append("] (\n");
        boolean hasIdentity = false;
        List<String[]> dataCols = new ArrayList<>();
        for (String[] col : cols) {
            if (col[7].equals("1")) continue;
            dataCols.add(col);
            if (col[6].equals("1")) hasIdentity = true;
            ddl.append("  [").append(col[0]).append("] ").append(colType(col[1], col[2], col[3], col[4]));
            if (col[6].equals("1")) ddl.append(" IDENTITY(1,1)");
            ddl.append(col[5].equals("1") ? " NULL" : " NOT NULL");
            if (col[8] != null && !col[8].isBlank()) ddl.append(" DEFAULT ").append(col[8]);
            ddl.append(",\n");
        }
        ddl.setLength(ddl.length() - 2);
        ddl.append("\n);\n");

        String colList = String.join(",", dataCols.stream().map(x -> "[" + x[0] + "]").toList());
        long rowCount = 0;
        try (Statement s = c.createStatement(); ResultSet rs = s.executeQuery("SELECT COUNT(*) FROM [" + table + "]")) {
            if (rs.next()) rowCount = rs.getLong(1);
        }
        if (rowCount > 0) {
            if (hasIdentity) ddl.append("SET IDENTITY_INSERT [").append(table).append("] ON;\n");
            List<String> rowsSql = new ArrayList<>();
            StringBuilder vals = new StringBuilder();
            int batch = 0;
            try (Statement s = c.createStatement(); ResultSet rs = s.executeQuery("SELECT " + colList + " FROM [" + table + "]")) {
                while (rs.next()) {
                    List<String> literals = new ArrayList<>();
                    for (int i = 0; i < dataCols.size(); i++) literals.add(literal(rs.getString(i + 1), dataCols.get(i)[1]));
                    if (vals.length() > 0) vals.append(",\n");
                    vals.append("(").append(String.join(",", literals)).append(")");
                    if (++batch >= 200) {
                        rowsSql.add("INSERT INTO [" + table + "] (" + colList + ") VALUES\n" + vals + ";");
                        vals.setLength(0); batch = 0;
                    }
                }
            }
            if (vals.length() > 0) rowsSql.add("INSERT INTO [" + table + "] (" + colList + ") VALUES\n" + vals + ";");
            for (String r : rowsSql) ddl.append(r).append("\n");
            if (hasIdentity) ddl.append("SET IDENTITY_INSERT [").append(table).append("] OFF;\n");
        }
        if (rowCount > 5000) System.out.println("  table " + table + " rows=" + rowCount);
        return ddl.toString();
    }

    static String literal(String v, String type) {
        if (v == null) return "NULL";
        switch (type) {
            case "int": case "bigint": case "smallint": case "tinyint":
            case "bit": case "decimal": case "numeric": case "money": case "smallmoney":
            case "float": case "real":
                return v;
            default:
                return "N'" + v.replace("'", "''") + "'";
        }
    }

    static String viewDdl(Connection c, String view) throws Exception {
        String sql = "SELECT definition FROM sys.sql_modules WHERE object_id = OBJECT_ID(?)";
        try (PreparedStatement ps = c.prepareStatement(sql)) {
            ps.setString(1, view);
            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next() && rs.getString(1) != null) {
                    String def = rs.getString(1).replaceFirst("(?i)CREATE\\s+VIEW", "CREATE OR ALTER VIEW").trim();
                    return def;
                }
            }
        }
        return "-- [view def missing] " + view;
    }
}
