# _i18n-planterm-keys.ps1 — 项目实施计划申请终止 二级审批 词条(状态+UI+4消息模板)补进 10 语言包(幂等;转义 \')
$ErrorActionPreference = 'Stop'
$dir = 'C:\INCER\YINJIA-MES\frontend\src\i18n\locales'
$K = @(
  '已终止', '终止审批中（立项人）', '终止审批中（管理员）',
  '申请终止', '终止审批通过', '终止审批驳回', '撤回终止申请',
  '终止于阶段', '发起人', '原因', '落实于', '终止原因（选填）',
  '已提交终止申请', '待立项人审批', '提交终止申请失败', '操作成功', '操作失败',
  '审批意见（选填）', '驳回须填写意见', '意见必填', '阶段'
)
$entries = @{
  'en'    = @{ '已终止'='Terminated'; '终止审批中（立项人）'='Termination Approval (Initiator)'; '终止审批中（管理员）'='Termination Approval (Admin)'; '申请终止'='Request Termination'; '终止审批通过'='Approve Termination'; '终止审批驳回'='Reject Termination'; '撤回终止申请'='Withdraw Termination Request'; '终止于阶段'='Terminate at stage'; '发起人'='Requested by'; '原因'='Reason'; '落实于'='Effective at'; '终止原因（选填）'='Termination reason (optional)'; '已提交终止申请'='Termination request submitted'; '待立项人审批'='awaiting initiator approval'; '提交终止申请失败'='Failed to submit termination request'; '操作成功'='Operation succeeded'; '操作失败'='Operation failed'; '审批意见（选填）'='Approval comment (optional)'; '驳回须填写意见'='A comment is required to reject'; '意见必填'='Comment is required'; '阶段'='Stage';
    '新的终止申请（待立项人审批）'='New termination request (initiator approval)'; '{actor} 申请终止「{panelName} {docNo}」（终止于阶段 {stage}），等待您（立项人）审批。'='{actor} requested termination of "{panelName} {docNo}" (at stage {stage}), awaiting your (initiator) approval.'; '终止申请待管理员审批'='Termination request awaiting admin approval'; '「{panelName} {docNo}」的终止申请（阶段 {stage}）已经立项人同意，等待管理员审批落实。'='The termination request for "{panelName} {docNo}" (stage {stage}) was approved by the initiator and awaits admin approval.'; '终止已落实'='Termination effected'; '「{panelName} {docNo}」的终止申请（阶段 {stage}）已经管理员同意，终止已落实，单据已锁定。'='The termination request for "{panelName} {docNo}" (stage {stage}) was approved by the admin. Termination is in effect and the document is locked.'; '终止申请被驳回'='Termination request rejected'; '「{panelName} {docNo}」的终止申请（阶段 {stage}）被 {actor} 驳回。意见：{opinion}'='The termination request for "{panelName} {docNo}" (stage {stage}) was rejected by {actor}. Comment: {opinion}' }
  'zh-TW' = @{ '已终止'='已終止'; '终止审批中（立项人）'='終止審批中（立項人）'; '终止审批中（管理员）'='終止審批中（管理員）'; '申请终止'='申請終止'; '终止审批通过'='終止審批通過'; '终止审批驳回'='終止審批駁回'; '撤回终止申请'='撤回終止申請'; '终止于阶段'='終止於階段'; '发起人'='發起人'; '原因'='原因'; '落实于'='落實於'; '终止原因（选填）'='終止原因（選填）'; '已提交终止申请'='已提交終止申請'; '待立项人审批'='待立項人審批'; '提交终止申请失败'='提交終止申請失敗'; '操作成功'='操作成功'; '操作失败'='操作失敗'; '审批意见（选填）'='審批意見（選填）'; '驳回须填写意见'='駁回須填寫意見'; '意见必填'='意見必填'; '阶段'='階段';
    '新的终止申请（待立项人审批）'='新的終止申請（待立項人審批）'; '{actor} 申请终止「{panelName} {docNo}」（终止于阶段 {stage}），等待您（立项人）审批。'='{actor} 申請終止「{panelName} {docNo}」（終止於階段 {stage}），等待您（立項人）審批。'; '终止申请待管理员审批'='終止申請待管理員審批'; '「{panelName} {docNo}」的终止申请（阶段 {stage}）已经立项人同意，等待管理员审批落实。'='「{panelName} {docNo}」的終止申請（階段 {stage}）已經立項人同意，等待管理員審批落實。'; '终止已落实'='終止已落實'; '「{panelName} {docNo}」的终止申请（阶段 {stage}）已经管理员同意，终止已落实，单据已锁定。'='「{panelName} {docNo}」的終止申請（階段 {stage}）已經管理員同意，終止已落實，單據已鎖定。'; '终止申请被驳回'='終止申請被駁回'; '「{panelName} {docNo}」的终止申请（阶段 {stage}）被 {actor} 驳回。意见：{opinion}'='「{panelName} {docNo}」的終止申請（階段 {stage}）被 {actor} 駁回。意見：{opinion}' }
  'ja'    = @{ '已终止'='終了済み'; '终止审批中（立项人）'='終了承認中（立項者）'; '终止审批中（管理员）'='終了承認中（管理者）'; '申请终止'='終了申請'; '终止审批通过'='終了承認承諾'; '终止审批驳回'='終了承認却下'; '撤回终止申请'='終了申請取下'; '终止于阶段'='段階で終了'; '发起人'='申請者'; '原因'='理由'; '落实于'='発効日時'; '终止原因（选填）'='終了理由（任意）'; '已提交终止申请'='終了申請を提出しました'; '待立项人审批'='立項者の承認待ち'; '提交终止申请失败'='終了申請の提出に失敗'; '操作成功'='操作しました'; '操作失败'='操作失敗'; '审批意见（选填）'='承認コメント（任意）'; '驳回须填写意见'='却下にはコメント必須'; '意见必填'='コメント必須'; '阶段'='段階';
    '新的终止申请（待立项人审批）'='新しい終了申請（立項者承認待ち）'; '{actor} 申请终止「{panelName} {docNo}」（终止于阶段 {stage}），等待您（立项人）审批。'='{actor} が「{panelName} {docNo}」の終了（段階 {stage}）を申請しました。立項者として承認してください。'; '终止申请待管理员审批'='終了申請は管理者承認待ち'; '「{panelName} {docNo}」的终止申请（阶段 {stage}）已经立项人同意，等待管理员审批落实。'='「{panelName} {docNo}」の終了申請（段階 {stage}）は立項者の同意済み、管理者の承認を待っています。'; '终止已落实'='終了済み'; '「{panelName} {docNo}」的终止申请（阶段 {stage}）已经管理员同意，终止已落实，单据已锁定。'='「{panelName} {docNo}」の終了申請（段階 {stage}）は管理者が同意し、終了が確定、伝票はロックされました。'; '终止申请被驳回'='終了申請が却下されました'; '「{panelName} {docNo}」的终止申请（阶段 {stage}）被 {actor} 驳回。意见：{opinion}'='「{panelName} {docNo}」の終了申請（段階 {stage}）は {actor} に却下されました。意見：{opinion}' }
  'ko'    = @{ '已终止'='종료됨'; '终止审批中（立项人）'='종료 승인중(입항자)'; '终止审批中（管理员）'='종료 승인중(관리자)'; '申请终止'='종료 신청'; '终止审批通过'='종료 승인'; '终止审批驳回'='종료 반려'; '撤回终止申请'='종료 신청 철회'; '终止于阶段'='단계에서 종료'; '发起人'='신청자'; '原因'='사유'; '落实于'='시점'; '终止原因（选填）'='종료 사유(선택)'; '已提交终止申请'='종료 신청 완료'; '待立项人审批'='입항자 승인 대기'; '提交终止申请失败'='종료 신청 실패'; '操作成功'='성공'; '操作失败'='실패'; '审批意见（选填）'='승인 의견(선택)'; '驳回须填写意见'='반려 시 의견 필수'; '意见必填'='의견 필수'; '阶段'='단계';
    '新的终止申请（待立项人审批）'='새 종료 신청(입항자 승인 대기)'; '{actor} 申请终止「{panelName} {docNo}」（终止于阶段 {stage}），等待您（立项人）审批。'='{actor} 님이 "{panelName} {docNo}"의 종료(단계 {stage})를 신청했습니다. 입항자로서 승인해 주세요.'; '终止申请待管理员审批'='종료 신청 관리자 승인 대기'; '「{panelName} {docNo}」的终止申请（阶段 {stage}）已经立项人同意，等待管理员审批落实。'='"{panelName} {docNo}"의 종료 신청(단계 {stage})이 입항자 동의를 받았으며 관리자 승인 대기 중입니다.'; '终止已落实'='종료 확정'; '「{panelName} {docNo}」的终止申请（阶段 {stage}）已经管理员同意，终止已落实，单据已锁定。'='"{panelName} {docNo}"의 종료 신청(단계 {stage})이 관리자 승인으로 확정되어 전표가 잠겼습니다.'; '终止申请被驳回'='종료 신청 반려됨'; '「{panelName} {docNo}」的终止申请（阶段 {stage}）被 {actor} 驳回。意见：{opinion}'='"{panelName} {docNo}"의 종료 신청(단계 {stage})이 {actor}에 의해 반려되었습니다. 의견: {opinion}' }
  'es'    = @{ '已终止'='Terminado'; '终止审批中（立项人）'='Aprobación de término (iniciador)'; '终止审批中（管理员）'='Aprobación de término (admin)'; '申请终止'='Solicitar término'; '终止审批通过'='Aprobar término'; '终止审批驳回'='Rechazar término'; '撤回终止申请'='Retirar solicitud'; '终止于阶段'='Terminar en etapa'; '发起人'='Solicitante'; '原因'='Motivo'; '落实于'='Efectivo el'; '终止原因（选填）'='Motivo del término (opcional)'; '已提交终止申请'='Solicitud enviada'; '待立项人审批'='pendiente aprobación del iniciador'; '提交终止申请失败'='Error al enviar'; '操作成功'='Operación exitosa'; '操作失败'='Operación fallida'; '审批意见（选填）'='Comentario (opcional)'; '驳回须填写意见'='Se requiere comentario para rechazar'; '意见必填'='Comentario obligatorio'; '阶段'='Etapa';
    '新的终止申请（待立项人审批）'='Nueva solicitud de término (aprobación del iniciador)'; '{actor} 申请终止「{panelName} {docNo}」（终止于阶段 {stage}），等待您（立项人）审批。'='{actor} solicitó terminar "{panelName} {docNo}" (etapa {stage}), esperando su aprobación (iniciador).'; '终止申请待管理员审批'='Solicitud de término pendiente del admin'; '「{panelName} {docNo}」的终止申请（阶段 {stage}）已经立项人同意，等待管理员审批落实。'='La solicitud de término de "{panelName} {docNo}" (etapa {stage}) fue aprobada por el iniciador y espera al admin.'; '终止已落实'='Término efectivo'; '「{panelName} {docNo}」的终止申请（阶段 {stage}）已经管理员同意，终止已落实，单据已锁定。'='La solicitud de término de "{panelName} {docNo}" (etapa {stage}) fue aprobada por el admin; el documento quedó bloqueado.'; '终止申请被驳回'='Solicitud rechazada'; '「{panelName} {docNo}」的终止申请（阶段 {stage}）被 {actor} 驳回。意见：{opinion}'='La solicitud de término de "{panelName} {docNo}" (etapa {stage}) fue rechazada por {actor}. Comentario: {opinion}' }
  'fr'    = @{ '已终止'='Terminé'; '终止审批中（立项人）'="Approbation d'arrêt (initiateur)"; '终止审批中（管理员）'="Approbation d'arrêt (admin)"; '申请终止'="Demander l'arrêt"; '终止审批通过'="Approuver l'arrêt"; '终止审批驳回'="Rejeter l'arrêt"; '撤回终止申请'='Retirer la demande'; '终止于阶段'='Arrêt à l''étape'; '发起人'='Demandeur'; '原因'='Motif'; '落实于'='Effectif le'; '终止原因（选填）'="Motif d'arrêt (facultatif)"; '已提交终止申请'='Demande envoyée'; '待立项人审批'="en attente de l'initiateur"; '提交终止申请失败'="Échec d'envoi"; '操作成功'='Opération réussie'; '操作失败'="Échec de l'opération"; '审批意见（选填）'='Commentaire (facultatif)'; '驳回须填写意见'='Commentaire requis pour rejeter'; '意见必填'='Commentaire requis'; '阶段'='Étape';
    '新的终止申请（待立项人审批）'="Nouvelle demande d'arrêt (initiateur)"; '{actor} 申请终止「{panelName} {docNo}」（终止于阶段 {stage}），等待您（立项人）审批。'='{actor} demande l''arrêt de « {panelName} {docNo} » (étape {stage}), en attente de votre approbation (initiateur).'; '终止申请待管理员审批'="Demande d'arrêt en attente de l'admin"; '「{panelName} {docNo}」的终止申请（阶段 {stage}）已经立项人同意，等待管理员审批落实。'="La demande d'arrêt de « {panelName} {docNo} » (étape {stage}) est approuvée par l'initiateur et attend l'admin."; '终止已落实'='Arrêt effectif'; '「{panelName} {docNo}」的终止申请（阶段 {stage}）已经管理员同意，终止已落实，单据已锁定。'="La demande d'arrêt de « {panelName} {docNo} » (étape {stage}) est approuvée par l'admin ; la fiche est verrouillée."; '终止申请被驳回'='Demande rejetée'; '「{panelName} {docNo}」的终止申请（阶段 {stage}）被 {actor} 驳回。意见：{opinion}'="La demande d'arrêt de « {panelName} {docNo} » (étape {stage}) a été rejetée par {actor}. Commentaire : {opinion}" }
  'de'    = @{ '已终止'='Beendet'; '终止审批中（立项人）'='Abschlussfreigabe (Initiator)'; '终止审批中（管理员）'='Abschlussfreigabe (Admin)'; '申请终止'='Abschluss beantragen'; '终止审批通过'='Abschluss genehmigen'; '终止审批驳回'='Abschluss ablehnen'; '撤回终止申请'='Antrag zurückziehen'; '终止于阶段'='Abschluss bei Stufe'; '发起人'='Antragsteller'; '原因'='Grund'; '落实于'='Wirksam am'; '终止原因（选填）'='Grund (optional)'; '已提交终止申请'='Antrag eingereicht'; '待立项人审批'='wartet auf Initiator'; '提交终止申请失败'='Einreichung fehlgeschlagen'; '操作成功'='Erfolgreich'; '操作失败'='Fehlgeschlagen'; '审批意见（选填）'='Kommentar (optional)'; '驳回须填写意见'='Zum Ablehnen ist ein Kommentar nötig'; '意见必填'='Kommentar erforderlich'; '阶段'='Stufe';
    '新的终止申请（待立项人审批）'='Neuer Abschlussantrag (Initiator)'; '{actor} 申请终止「{panelName} {docNo}」（终止于阶段 {stage}），等待您（立项人）审批。'='{actor} beantragt den Abschluss von „{panelName} {docNo}“ (Stufe {stage}) und wartet auf Ihre Freigabe (Initiator).'; '终止申请待管理员审批'='Abschlussantrag wartet auf Admin'; '「{panelName} {docNo}」的终止申请（阶段 {stage}）已经立项人同意，等待管理员审批落实。'='Der Abschlussantrag für „{panelName} {docNo}“ (Stufe {stage}) ist vom Initiator freigegeben und wartet auf den Admin.'; '终止已落实'='Abschluss wirksam'; '「{panelName} {docNo}」的终止申请（阶段 {stage}）已经管理员同意，终止已落实，单据已锁定。'='Der Abschlussantrag für „{panelName} {docNo}“ (Stufe {stage}) wurde vom Admin genehmigt; der Bogen ist gesperrt.'; '终止申请被驳回'='Antrag abgelehnt'; '「{panelName} {docNo}」的终止申请（阶段 {stage}）被 {actor} 驳回。意见：{opinion}'='Der Abschlussantrag für „{panelName} {docNo}“ (Stufe {stage}) wurde von {actor} abgelehnt. Kommentar: {opinion}' }
  'ru'    = @{ '已终止'='Прекращено'; '终止审批中（立项人）'='Согласование прекращения (инициатор)'; '终止审批中（管理员）'='Согласование прекращения (админ)'; '申请终止'='Заявить о прекращении'; '终止审批通过'='Согласовать прекращение'; '终止审批驳回'='Отклонить прекращение'; '撤回终止申请'='Отозвать заявку'; '终止于阶段'='Прекращение на этапе'; '发起人'='Заявитель'; '原因'='Причина'; '落实于'='Вступило в силу'; '终止原因（选填）'='Причина (необязательно)'; '已提交终止申请'='Заявка подана'; '待立项人审批'='ожидает инициатора'; '提交终止申请失败'='Не удалось подать заявку'; '操作成功'='Успешно'; '操作失败'='Ошибка операции'; '审批意见（选填）'='Комментарий (необязательно)'; '驳回须填写意见'='Для отклонения нужен комментарий'; '意见必填'='Комментарий обязателен'; '阶段'='Этап';
    '新的终止申请（待立项人审批）'='Новая заявка на прекращение (инициатор)'; '{actor} 申请终止「{panelName} {docNo}」（终止于阶段 {stage}），等待您（立项人）审批。'='{actor} подал заявку на прекращение «{panelName} {docNo}» (этап {stage}) и ждёт вашего согласования (инициатор).'; '终止申请待管理员审批'='Заявка ожидает админа'; '「{panelName} {docNo}」的终止申请（阶段 {stage}）已经立项人同意，等待管理员审批落实。'='Заявка на прекращение «{panelName} {docNo}» (этап {stage}) согласована инициатором и ждёт админа.'; '终止已落实'='Прекращение вступило в силу'; '「{panelName} {docNo}」的终止申请（阶段 {stage}）已经管理员同意，终止已落实，单据已锁定。'='Заявка на прекращение «{panelName} {docNo}» (этап {stage}) согласована админом; лист заблокирован.'; '终止申请被驳回'='Заявка отклонена'; '「{panelName} {docNo}」的终止申请（阶段 {stage}）被 {actor} 驳回。意见：{opinion}'='Заявка на прекращение «{panelName} {docNo}» (этап {stage}) отклонена {actor}. Комментарий: {opinion}' }
  'vi'    = @{ '已终止'='Đã chấm dứt'; '终止审批中（立项人）'='Duyệt chấm dứt (người lập)'; '终止审批中（管理员）'='Duyệt chấm dứt (QLV)'; '申请终止'='Xin chấm dứt'; '终止审批通过'='Duyệt chấm dứt'; '终止审批驳回'='Từ chối chấm dứt'; '撤回终止申请'='Rút đơn xin'; '终止于阶段'='Chấm dứt ở giai đoạn'; '发起人'='Người xin'; '原因'='Lý do'; '落实于'='Hiệu lực lúc'; '终止原因（选填）'='Lý do (không bắt buộc)'; '已提交终止申请'='Đã nộp đơn'; '待立项人审批'='chờ người lập duyệt'; '提交终止申请失败'='Nộp đơn thất bại'; '操作成功'='Thành công'; '操作失败'='Thất bại'; '审批意见（选填）'='Ý kiến (không bắt buộc)'; '驳回须填写意见'='Từ chối phải có ý kiến'; '意见必填'='Bắt buộc ý kiến'; '阶段'='Giai đoạn';
    '新的终止申请（待立项人审批）'='Đơn xin chấm dứt mới (chờ người lập)'; '{actor} 申请终止「{panelName} {docNo}」（终止于阶段 {stage}），等待您（立项人）审批。'='{actor} xin chấm dứt "{panelName} {docNo}" (giai đoạn {stage}), chờ bạn (người lập) duyệt.'; '终止申请待管理员审批'='Đơn chấm dứt chờ QLV duyệt'; '「{panelName} {docNo}」的终止申请（阶段 {stage}）已经立项人同意，等待管理员审批落实。'='Đơn chấm dứt của "{panelName} {docNo}" (giai đoạn {stage}) đã được người lập đồng ý, chờ QLV.'; '终止已落实'='Đã chấm dứt'; '「{panelName} {docNo}」的终止申请（阶段 {stage}）已经管理员同意，终止已落实，单据已锁定。'='Đơn chấm dứt của "{panelName} {docNo}" (giai đoạn {stage}) đã được QLV đồng ý; chứng từ đã khóa.'; '终止申请被驳回'='Đơn bị từ chối'; '「{panelName} {docNo}」的终止申请（阶段 {stage}）被 {actor} 驳回。意见：{opinion}'='Đơn chấm dứt của "{panelName} {docNo}" (giai đoạn {stage}) bị {actor} từ chối. Ý kiến: {opinion}' }
  'th'    = @{ '已终止'='สิ้นสุดแล้ว'; '终止审批中（立项人）'='อนุมัติการสิ้นสุด (ผู้ริเริ่ม)'; '终止审批中（管理员）'='อนุมัติการสิ้นสุด (แอดมิน)'; '申请终止'='ขอสิ้นสุด'; '终止审批通过'='อนุมัติการสิ้นสุด'; '终止审批驳回'='ปฏิเสธการสิ้นสุด'; '撤回终止申请'='ถอนคำขอ'; '终止于阶段'='สิ้นสุดที่ขั้น'; '发起人'='ผู้ขอ'; '原因'='เหตุผล'; '落实于'='มีผลเมื่อ'; '终止原因（选填）'='เหตุผล (ไม่บังคับ)'; '已提交终止申请'='ส่งคำขอแล้ว'; '待立项人审批'='รอผู้ริเริ่มอนุมัติ'; '提交终止申请失败'='ส่งคำขอไม่สำเร็จ'; '操作成功'='สำเร็จ'; '操作失败'='ล้มเหลว'; '审批意见（选填）'='ความเห็น (ไม่บังคับ)'; '驳回须填写意见'='ปฏิเสธต้องมีความเห็น'; '意见必填'='ต้องกรอกความเห็น'; '阶段'='ขั้น';
    '新的终止申请（待立项人审批）'='คำขอสิ้นสุดใหม่ (รอผู้ริเริ่ม)'; '{actor} 申请终止「{panelName} {docNo}」（终止于阶段 {stage}），等待您（立项人）审批。'='{actor} ขอสิ้นสุด "{panelName} {docNo}" (ขั้น {stage}) รอคุณ (ผู้ริเริ่ม) อนุมัติ'; '终止申请待管理员审批'='คำขอสิ้นสุดรอแอดมินอนุมัติ'; '「{panelName} {docNo}」的终止申请（阶段 {stage}）已经立项人同意，等待管理员审批落实。'='คำขอสิ้นสุดของ "{panelName} {docNo}" (ขั้น {stage}) ผู้ริเริ่มเห็นชอบแล้ว รอแอดมินอนุมัติ'; '终止已落实'='สิ้นสุดแล้ว'; '「{panelName} {docNo}」的终止申请（阶段 {stage}）已经管理员同意，终止已落实，单据已锁定。'='คำขอสิ้นสุดของ "{panelName} {docNo}" (ขั้น {stage}) แอดมินเห็นชอบ เอกสารถูกล็อกแล้ว'; '终止申请被驳回'='คำขอถูกปฏิเสธ'; '「{panelName} {docNo}」的终止申请（阶段 {stage}）被 {actor} 驳回。意见：{opinion}'='คำขอสิ้นสุดของ "{panelName} {docNo}" (ขั้น {stage}) ถูก {actor} ปฏิเสธ ความเห็น: {opinion}' }
}
# 全部键 = 状态/UI 键数组 + 消息模板键(取 en 哈希键集,免内联长数组)
$allKeys = @($K) + @($entries['en'].Keys)
foreach ($loc in $entries.Keys) {
  $file = Join-Path $dir "$loc.js"
  $text = [System.IO.File]::ReadAllText($file, [System.Text.UTF8Encoding]::new($false))
  $anchor = $text.LastIndexOf("`n  },")
  if ($anchor -lt 0) { Write-Host "[$loc] ANCHOR NOT FOUND"; continue }
  $lines = New-Object System.Text.StringBuilder
  $added = 0
  foreach ($k in $allKeys) {
    if ($text.Contains("'" + $k + "':")) { continue }
    $v = $entries[$loc][$k]
    if ($null -eq $v) { continue }
    [void]$lines.Append("    '$k': '$($v.Replace("'", "\'"))',`n")
    $added++
  }
  if ($added -gt 0) {
    $text = $text.Insert($anchor + 1, $lines.ToString())
    [System.IO.File]::WriteAllText($file, $text, [System.Text.UTF8Encoding]::new($false))
  }
  Write-Host "[$loc] +$added keys"
}
Write-Host 'done'
