-- 通用报表铺开探针取样:每个待验面板取 1 个真实单据号(只读,不写库)
SET NOCOUNT ON;
SELECT 'SO_ORDER' AS panel, (SELECT TOP 1 RTRIM(LTRIM([单据编号])) FROM bl_so_order ORDER BY id DESC) AS no
UNION ALL SELECT 'PU_ORDER', (SELECT TOP 1 RTRIM(LTRIM([单据编号])) FROM bl_pu_order ORDER BY id DESC)
UNION ALL SELECT 'PURCHASE_IN', (SELECT TOP 1 RTRIM(LTRIM([单据编号])) FROM bl_purchase_in ORDER BY id DESC)
UNION ALL SELECT 'MANU_ORDER', (SELECT TOP 1 RTRIM(LTRIM([合同号])) FROM bd_manu_order ORDER BY id DESC)
UNION ALL SELECT 'SALE_OUT', (SELECT TOP 1 RTRIM(LTRIM([单据编号])) FROM bl_sale_out ORDER BY id DESC)
UNION ALL SELECT 'RKD', (SELECT TOP 1 RTRIM(LTRIM([inh_no])) FROM inh ORDER BY id DESC)
UNION ALL SELECT 'CKD', (SELECT TOP 1 RTRIM(LTRIM([outh_no])) FROM outh ORDER BY id DESC)
UNION ALL SELECT 'GRAN_RECORD', (SELECT TOP 1 RTRIM(LTRIM([单据编号])) FROM gran_record ORDER BY id DESC)
UNION ALL SELECT 'PR_MIX_DAILY', (SELECT TOP 1 RTRIM(LTRIM([单据编号])) FROM pr_mix_daily ORDER BY id DESC)
UNION ALL SELECT 'OTHER_IN', (SELECT TOP 1 RTRIM(LTRIM([单据编号])) FROM bd_other_in ORDER BY id DESC)
UNION ALL SELECT 'OUTSOURCE_ORDER', (SELECT TOP 1 RTRIM(LTRIM([单据编号])) FROM bl_outsource_order ORDER BY id DESC)
UNION ALL SELECT 'WLBOM', (SELECT TOP 1 RTRIM(LTRIM([m_no])) FROM mate ORDER BY id DESC)
UNION ALL SELECT 'WO_ORDER', (SELECT TOP 1 RTRIM(LTRIM([单据编号])) FROM wo_progress ORDER BY id DESC)
UNION ALL SELECT 'QC_OP', (SELECT TOP 1 RTRIM(LTRIM([单据编号])) FROM qc_op_detail ORDER BY id DESC)
UNION ALL SELECT 'DAY_REPORT', (SELECT TOP 1 RTRIM(LTRIM([单据编号])) FROM day_report_detail ORDER BY id DESC)
UNION ALL SELECT 'WO_REPORT', (SELECT TOP 1 RTRIM(LTRIM([单据编号])) FROM wo_report ORDER BY id DESC)
UNION ALL SELECT 'QC_DISPOSAL', (SELECT TOP 1 RTRIM(LTRIM([单据编号])) FROM qc_disposal ORDER BY id DESC);
