-- PANDA 一比一复刻后字段标签译名补录(§3.1 多语言开发规范:新增/改名字段必须同步译名)
-- 覆盖:复刻新增列(制单人/创建时间/主辅单位系列/布局列等)+ 既有缺口(预计交货日期/销售单位/单据状态等)
-- 幂等:MERGE 仅补缺失行,不动已有 manual/mt 译名;locale 覆盖 en/ja/ko/de/es/fr/ru/th/vi
-- 执行:sqlcmd -f 65001(UTF-8 无 BOM,见 docs/development/开发与质量.md §3.1)
USE HSDZ_MES;
SET NOCOUNT ON;

MERGE yj_translation AS t USING (VALUES
(N'制单人',N'en',N'Prepared by'),(N'制单人',N'ja',N'作成者'),(N'制单人',N'ko',N'작성자'),(N'制单人',N'de',N'Erstellt von'),(N'制单人',N'es',N'Elaborado por'),(N'制单人',N'fr',N'Établi par'),(N'制单人',N'ru',N'Составил'),(N'制单人',N'th',N'ผู้จัดทำ'),(N'制单人',N'vi',N'Người lập'),
(N'创建时间',N'en',N'Created at'),(N'创建时间',N'ja',N'作成時間'),(N'创建时间',N'ko',N'생성 시간'),(N'创建时间',N'de',N'Erstellt am'),(N'创建时间',N'es',N'Fecha de creación'),(N'创建时间',N'fr',N'Créé le'),(N'创建时间',N'ru',N'Время создания'),(N'创建时间',N'th',N'เวลาสร้าง'),(N'创建时间',N'vi',N'Thời gian tạo'),
(N'审核人',N'en',N'Approved by'),(N'审核人',N'ja',N'承認者'),(N'审核人',N'ko',N'승인자'),(N'审核人',N'de',N'Genehmigt von'),(N'审核人',N'es',N'Aprobado por'),(N'审核人',N'fr',N'Approuvé par'),(N'审核人',N'ru',N'Утвердил'),(N'审核人',N'th',N'ผู้อนุมัติ'),(N'审核人',N'vi',N'Người duyệt'),
(N'审核时间',N'en',N'Approved at'),(N'审核时间',N'ja',N'承認時間'),(N'审核时间',N'ko',N'승인 시간'),(N'审核时间',N'de',N'Genehmigt am'),(N'审核时间',N'es',N'Fecha de aprobación'),(N'审核时间',N'fr',N'Date d''approbation'),(N'审核时间',N'ru',N'Время утверждения'),(N'审核时间',N'th',N'เวลาอนุมัติ'),(N'审核时间',N'vi',N'Thời gian duyệt'),
(N'审批人',N'en',N'Approved by (workflow)'),(N'审批人',N'ja',N'決裁者'),(N'审批人',N'ko',N'결재자'),(N'审批人',N'de',N'Freigeber'),(N'审批人',N'es',N'Aprobador'),(N'审批人',N'fr',N'Approbateur'),(N'审批人',N'ru',N'Согласовал'),(N'审批人',N'th',N'ผู้พิจารณา'),(N'审批人',N'vi',N'Người phê duyệt'),
(N'审批时间',N'en',N'Approved at (workflow)'),(N'审批时间',N'ja',N'決裁時間'),(N'审批时间',N'ko',N'결재 시간'),(N'审批时间',N'de',N'Freigabezeit'),(N'审批时间',N'es',N'Hora de aprobación'),(N'审批时间',N'fr',N'Heure d''approbation'),(N'审批时间',N'ru',N'Время согласования'),(N'审批时间',N'th',N'เวลาพิจารณา'),(N'审批时间',N'vi',N'Thời gian phê duyệt'),
(N'单据状态',N'en',N'Doc status'),(N'单据状态',N'ja',N'伝票ステータス'),(N'单据状态',N'ko',N'전표 상태'),(N'单据状态',N'de',N'Belegstatus'),(N'单据状态',N'es',N'Estado documento'),(N'单据状态',N'fr',N'Statut document'),(N'单据状态',N'ru',N'Статус документа'),(N'单据状态',N'th',N'สถานะเอกสาร'),(N'单据状态',N'vi',N'Trạng thái chứng từ'),
(N'单据数',N'en',N'Doc count'),(N'单据数',N'ja',N'伝票数'),(N'单据数',N'ko',N'전표 수'),(N'单据数',N'de',N'Beleganzahl'),(N'单据数',N'es',N'N.º documentos'),(N'单据数',N'fr',N'Nb documents'),(N'单据数',N'ru',N'Кол-во документов'),(N'单据数',N'th',N'จำนวนเอกสาร'),(N'单据数',N'vi',N'Số chứng từ'),
(N'单据日期（周）',N'en',N'Doc date (week)'),(N'单据日期（周）',N'ja',N'伝票日付（週）'),(N'单据日期（周）',N'ko',N'전표 일자(주)'),(N'单据日期（周）',N'de',N'Belegdatum (Woche)'),(N'单据日期（周）',N'es',N'Fecha documento (semana)'),(N'单据日期（周）',N'fr',N'Date document (semaine)'),(N'单据日期（周）',N'ru',N'Дата документа (неделя)'),(N'单据日期（周）',N'th',N'วันที่เอกสาร(สัปดาห์)'),(N'单据日期（周）',N'vi',N'Ngày chứng từ (tuần)'),
(N'存货',N'en',N'Inventory'),(N'存货',N'ja',N'存貨'),(N'存货',N'ko',N'재고'),(N'存货',N'de',N'Artikel'),(N'存货',N'es',N'Artículo'),(N'存货',N'fr',N'Article'),(N'存货',N'ru',N'Номенклатура'),(N'存货',N'th',N'สินค้า'),(N'存货',N'vi',N'Hàng tồn'),
(N'材料',N'en',N'Material'),(N'材料',N'ja',N'材料'),(N'材料',N'ko',N'자재'),(N'材料',N'de',N'Material'),(N'材料',N'es',N'Material'),(N'材料',N'fr',N'Matériau'),(N'材料',N'ru',N'Материал'),(N'材料',N'th',N'วัสดุ'),(N'材料',N'vi',N'Vật liệu'),
(N'材料规格',N'en',N'Material spec'),(N'材料规格',N'ja',N'材料仕様'),(N'材料规格',N'ko',N'자재 규격'),(N'材料规格',N'de',N'Materialspezifikation'),(N'材料规格',N'es',N'Especificación material'),(N'材料规格',N'fr',N'Spécification matériau'),(N'材料规格',N'ru',N'Спецификация материала'),(N'材料规格',N'th',N'สเปกวัสดุ'),(N'材料规格',N'vi',N'Quy cách vật liệu'),
(N'存货名称.品牌',N'en',N'Item name.brand'),(N'存货名称.品牌',N'ja',N'品名.ブランド'),(N'存货名称.品牌',N'ko',N'품명.브랜드'),(N'存货名称.品牌',N'de',N'Artikelname.Marke'),(N'存货名称.品牌',N'es',N'Nombre artículo.marca'),(N'存货名称.品牌',N'fr',N'Nom article.marque'),(N'存货名称.品牌',N'ru',N'Наименование.Бренд'),(N'存货名称.品牌',N'th',N'ชื่อสินค้า.ยี่ห้อ'),(N'存货名称.品牌',N'vi',N'Tên hàng.thương hiệu'),
(N'主单位',N'en',N'Main unit'),(N'主单位',N'ja',N'主単位'),(N'主单位',N'ko',N'주단위'),(N'主单位',N'de',N'Haupteinheit'),(N'主单位',N'es',N'Unidad principal'),(N'主单位',N'fr',N'Unité principale'),(N'主单位',N'ru',N'Осн. единица'),(N'主单位',N'th',N'หน่วยหลัก'),(N'主单位',N'vi',N'Đơn vị chính'),
(N'辅单位',N'en',N'Aux unit'),(N'辅单位',N'ja',N'補助単位'),(N'辅单位',N'ko',N'보조단위'),(N'辅单位',N'de',N'Hilfseinheit'),(N'辅单位',N'es',N'Unidad auxiliar'),(N'辅单位',N'fr',N'Unité auxiliaire'),(N'辅单位',N'ru',N'Всп. единица'),(N'辅单位',N'th',N'หน่วยรอง'),(N'辅单位',N'vi',N'Đơn vị phụ'),
(N'计量单位(辅单位)',N'en',N'UOM (aux)'),(N'计量单位(辅单位)',N'ja',N'計量単位(補助)'),(N'计量单位(辅单位)',N'ko',N'계량단위(보조)'),(N'计量单位(辅单位)',N'de',N'ME (Hilfseinheit)'),(N'计量单位(辅单位)',N'es',N'UM (aux)'),(N'计量单位(辅单位)',N'fr',N'UU (aux)'),(N'计量单位(辅单位)',N'ru',N'Ед. изм. (всп.)'),(N'计量单位(辅单位)',N'th',N'หน่วยวัด(หน่วยรอง)'),(N'计量单位(辅单位)',N'vi',N'ĐVT (phụ)'),
(N'数量(主单位)',N'en',N'Qty (main)'),(N'数量(主单位)',N'ja',N'数量(主単位)'),(N'数量(主单位)',N'ko',N'수량(주단위)'),(N'数量(主单位)',N'de',N'Menge (Haupteinheit)'),(N'数量(主单位)',N'es',N'Cantidad (principal)'),(N'数量(主单位)',N'fr',N'Qté (principale)'),(N'数量(主单位)',N'ru',N'Кол-во (осн.)'),(N'数量(主单位)',N'th',N'ปริมาณ(หน่วยหลัก)'),(N'数量(主单位)',N'vi',N'SL (chính)'),
(N'数量(辅单位)',N'en',N'Qty (aux)'),(N'数量(辅单位)',N'ja',N'数量(補助単位)'),(N'数量(辅单位)',N'ko',N'수량(보조단위)'),(N'数量(辅单位)',N'de',N'Menge (Hilfseinheit)'),(N'数量(辅单位)',N'es',N'Cantidad (auxiliar)'),(N'数量(辅单位)',N'fr',N'Qté (auxiliaire)'),(N'数量(辅单位)',N'ru',N'Кол-во (всп.)'),(N'数量(辅单位)',N'th',N'ปริมาณ(หน่วยรอง)'),(N'数量(辅单位)',N'vi',N'SL (phụ)'),
(N'实收数量(主单位)',N'en',N'Received qty (main)'),(N'实收数量(主单位)',N'ja',N'実受数量(主単位)'),(N'实收数量(主单位)',N'ko',N'실수량(주단위)'),(N'实收数量(主单位)',N'de',N'Erhaltene Menge (Haupteinheit)'),(N'实收数量(主单位)',N'es',N'Cant. recibida (principal)'),(N'实收数量(主单位)',N'fr',N'Qté reçue (principale)'),(N'实收数量(主单位)',N'ru',N'Принято (осн.)'),(N'实收数量(主单位)',N'th',N'ปริมาณรับจริง(หน่วยหลัก)'),(N'实收数量(主单位)',N'vi',N'SL nhận thực (chính)'),
(N'实收数量(辅单位)',N'en',N'Received qty (aux)'),(N'实收数量(辅单位)',N'ja',N'実受数量(補助単位)'),(N'实收数量(辅单位)',N'ko',N'실수량(보조단위)'),(N'实收数量(辅单位)',N'de',N'Erhaltene Menge (Hilfseinheit)'),(N'实收数量(辅单位)',N'es',N'Cant. recibida (auxiliar)'),(N'实收数量(辅单位)',N'fr',N'Qté reçue (auxiliaire)'),(N'实收数量(辅单位)',N'ru',N'Принято (всп.)'),(N'实收数量(辅单位)',N'th',N'ปริมาณรับจริง(หน่วยรอง)'),(N'实收数量(辅单位)',N'vi',N'SL nhận thực (phụ)'),
(N'单价(主单位)',N'en',N'Unit price (main)'),(N'单价(主单位)',N'ja',N'単価(主単位)'),(N'单价(主单位)',N'ko',N'단가(주단위)'),(N'单价(主单位)',N'de',N'Einzelpreis (Haupteinheit)'),(N'单价(主单位)',N'es',N'Precio unitario (principal)'),(N'单价(主单位)',N'fr',N'Prix unitaire (principal)'),(N'单价(主单位)',N'ru',N'Цена (осн.)'),(N'单价(主单位)',N'th',N'ราคาต่อหน่วย(หน่วยหลัก)'),(N'单价(主单位)',N'vi',N'Đơn giá (chính)'),
(N'单价(辅单位)',N'en',N'Unit price (aux)'),(N'单价(辅单位)',N'ja',N'単価(補助単位)'),(N'单价(辅单位)',N'ko',N'단가(보조단위)'),(N'单价(辅单位)',N'de',N'Einzelpreis (Hilfseinheit)'),(N'单价(辅单位)',N'es',N'Precio unitario (auxiliar)'),(N'单价(辅单位)',N'fr',N'Prix unitaire (auxiliaire)'),(N'单价(辅单位)',N'ru',N'Цена (всп.)'),(N'单价(辅单位)',N'th',N'ราคาต่อหน่วย(หน่วยรอง)'),(N'单价(辅单位)',N'vi',N'Đơn giá (phụ)'),
(N'成本价(主单位)',N'en',N'Unit cost (main)'),(N'成本价(主单位)',N'ja',N'単位原価(主単位)'),(N'成本价(主单位)',N'ko',N'단위원가(주단위)'),(N'成本价(主单位)',N'de',N'Einstandspreis (Haupteinheit)'),(N'成本价(主单位)',N'es',N'Coste unitario (principal)'),(N'成本价(主单位)',N'fr',N'Coût unitaire (principal)'),(N'成本价(主单位)',N'ru',N'Себестоимость (осн.)'),(N'成本价(主单位)',N'th',N'ต้นทุนต่อหน่วย(หน่วยหลัก)'),(N'成本价(主单位)',N'vi',N'Giá vốn (chính)'),
(N'成本价(辅单位)',N'en',N'Unit cost (aux)'),(N'成本价(辅单位)',N'ja',N'単位原価(補助単位)'),(N'成本价(辅单位)',N'ko',N'단위원가(보조단위)'),(N'成本价(辅单位)',N'de',N'Einstandspreis (Hilfseinheit)'),(N'成本价(辅单位)',N'es',N'Coste unitario (auxiliar)'),(N'成本价(辅单位)',N'fr',N'Coût unitaire (auxiliaire)'),(N'成本价(辅单位)',N'ru',N'Себестоимость (всп.)'),(N'成本价(辅单位)',N'th',N'ต้นทุนต่อหน่วย(หน่วยรอง)'),(N'成本价(辅单位)',N'vi',N'Giá vốn (phụ)'),
(N'成本金额',N'en',N'Cost amount'),(N'成本金额',N'ja',N'原価金額'),(N'成本金额',N'ko',N'원가 금액'),(N'成本金额',N'de',N'Kostenbetrag'),(N'成本金额',N'es',N'Importe de coste'),(N'成本金额',N'fr',N'Montant du coût'),(N'成本金额',N'ru',N'Сумма затрат'),(N'成本金额',N'th',N'จำนวนเงินต้นทุน'),(N'成本金额',N'vi',N'Tổng giá vốn'),
(N'总成本',N'en',N'Total cost'),(N'总成本',N'ja',N'総原価'),(N'总成本',N'ko',N'총원가'),(N'总成本',N'de',N'Gesamtkosten'),(N'总成本',N'es',N'Coste total'),(N'总成本',N'fr',N'Coût total'),(N'总成本',N'ru',N'Полная себестоимость'),(N'总成本',N'th',N'ต้นทุนรวม'),(N'总成本',N'vi',N'Tổng giá thành'),
(N'入库调整',N'en',N'Receipt adjustment'),(N'入库调整',N'ja',N'入庫調整'),(N'入库调整',N'ko',N'입고 조정'),(N'入库调整',N'de',N'Wareneingangsanpassung'),(N'入库调整',N'es',N'Ajuste de entrada'),(N'入库调整',N'fr',N'Ajustement d''entrée'),(N'入库调整',N'ru',N'Корректировка поступления'),(N'入库调整',N'th',N'ปรับปรุงการรับเข้า'),(N'入库调整',N'vi',N'Điều chỉnh nhập'),
(N'出库调整',N'en',N'Issue adjustment'),(N'出库调整',N'ja',N'出庫調整'),(N'出库调整',N'ko',N'출고 조정'),(N'出库调整',N'de',N'Warenausgangsanpassung'),(N'出库调整',N'es',N'Ajuste de salida'),(N'出库调整',N'fr',N'Ajustement de sortie'),(N'出库调整',N'ru',N'Корректировка отпуска'),(N'出库调整',N'th',N'ปรับปรุงการออก'),(N'出库调整',N'vi',N'Điều chỉnh xuất'),
(N'应发数量',N'en',N'Due qty'),(N'应发数量',N'ja',N'応出庫数量'),(N'应发数量',N'ko',N'지급 예정 수량'),(N'应发数量',N'de',N'Sollmenge'),(N'应发数量',N'es',N'Cantidad debida'),(N'应发数量',N'fr',N'Qté due'),(N'应发数量',N'ru',N'Подлежит отпуску'),(N'应发数量',N'th',N'ปริมาณที่ต้องจ่าย'),(N'应发数量',N'vi',N'SL phải xuất'),
(N'应发数量2',N'en',N'Due qty 2'),(N'应发数量2',N'ja',N'応出庫数量2'),(N'应发数量2',N'ko',N'지급 예정 수량2'),(N'应发数量2',N'de',N'Sollmenge 2'),(N'应发数量2',N'es',N'Cantidad debida 2'),(N'应发数量2',N'fr',N'Qté due 2'),(N'应发数量2',N'ru',N'Подлежит отпуску 2'),(N'应发数量2',N'th',N'ปริมาณที่ต้องจ่าย2'),(N'应发数量2',N'vi',N'SL phải xuất 2'),
(N'合理损耗数量',N'en',N'Reasonable loss qty'),(N'合理损耗数量',N'ja',N'合理損耗数量'),(N'合理损耗数量',N'ko',N'정상 손모 수량'),(N'合理损耗数量',N'de',N'Normalverlust'),(N'合理损耗数量',N'es',N'Merma razonable'),(N'合理损耗数量',N'fr',N'Perte raisonnable'),(N'合理损耗数量',N'ru',N'Норма потерь'),(N'合理损耗数量',N'th',N'ปริมาณสูญเสียตามปกติ'),(N'合理损耗数量',N'vi',N'Hao hụt hợp lý'),
(N'合理损耗数量(主单位)',N'en',N'Reasonable loss qty (main)'),(N'合理损耗数量(主单位)',N'ja',N'合理損耗数量(主単位)'),(N'合理损耗数量(主单位)',N'ko',N'정상 손모 수량(주단위)'),(N'合理损耗数量(主单位)',N'de',N'Normalverlust (Haupteinheit)'),(N'合理损耗数量(主单位)',N'es',N'Merma razonable (principal)'),(N'合理损耗数量(主单位)',N'fr',N'Perte raisonnable (principale)'),(N'合理损耗数量(主单位)',N'ru',N'Норма потерь (осн.)'),(N'合理损耗数量(主单位)',N'th',N'ปริมาณสูญเสียตามปกติ(หน่วยหลัก)'),(N'合理损耗数量(主单位)',N'vi',N'Hao hụt hợp lý (chính)'),
(N'累计调拨入库量',N'en',N'Cum. transfer-in qty'),(N'累计调拨入库量',N'ja',N'累計振替入庫量'),(N'累计调拨入库量',N'ko',N'누적 이동 입고량'),(N'累计调拨入库量',N'de',N'Kum. Umbuchungseingang'),(N'累计调拨入库量',N'es',N'Traslado acumulado'),(N'累计调拨入库量',N'fr',N'Transfert cumulé'),(N'累计调拨入库量',N'ru',N'Накопленный трансферт'),(N'累计调拨入库量',N'th',N'ปริมาณโอนเข้าสะสม'),(N'累计调拨入库量',N'vi',N'Lũy kế chuyển nhập'),
(N'累计调拨入库量(主单位)',N'en',N'Cum. transfer-in qty (main)'),(N'累计调拨入库量(主单位)',N'ja',N'累計振替入庫量(主単位)'),(N'累计调拨入库量(主单位)',N'ko',N'누적 이동 입고량(주단위)'),(N'累计调拨入库量(主单位)',N'de',N'Kum. Umbuchungseingang (Haupteinheit)'),(N'累计调拨入库量(主单位)',N'es',N'Traslado acumulado (principal)'),(N'累计调拨入库量(主单位)',N'fr',N'Transfert cumulé (principal)'),(N'累计调拨入库量(主单位)',N'ru',N'Накопленный трансфер (осн.)'),(N'累计调拨入库量(主单位)',N'th',N'ปริมาณโอนเข้าสะสม(หน่วยหลัก)'),(N'累计调拨入库量(主单位)',N'vi',N'Lũy kế chuyển nhập (chính)'),
(N'入库单数',N'en',N'Receipt count'),(N'入库单数',N'ja',N'入庫伝票数'),(N'入库单数',N'ko',N'입고 전표 수'),(N'入库单数',N'de',N'Wareneingänge'),(N'入库单数',N'es',N'N.º entradas'),(N'入库单数',N'fr',N'Nb entrées'),(N'入库单数',N'ru',N'Кол-во поступлений'),(N'入库单数',N'th',N'จำนวนใบรับเข้า'),(N'入库单数',N'vi',N'Số phiếu nhập'),
(N'发料单数',N'en',N'Issue count'),(N'发料单数',N'ja',N'発料伝票数'),(N'发料单数',N'ko',N'지급 전표 수'),(N'发料单数',N'de',N'Materialausgaben'),(N'发料单数',N'es',N'N.º emisiones'),(N'发料单数',N'fr',N'Nb sorties matière'),(N'发料单数',N'ru',N'Кол-во выдач'),(N'发料单数',N'th',N'จำนวนใบเบิก'),(N'发料单数',N'vi',N'Số phiếu cấp liệu'),
(N'加工单数',N'en',N'Work order count'),(N'加工单数',N'ja',N'加工伝票数'),(N'加工单数',N'ko',N'가공 전표 수'),(N'加工单数',N'de',N'Fertigungsaufträge'),(N'加工单数',N'es',N'N.º órdenes'),(N'加工单数',N'fr',N'Nb ordres'),(N'加工单数',N'ru',N'Кол-во заказов'),(N'加工单数',N'th',N'จำนวนใบสั่งผลิต'),(N'加工单数',N'vi',N'Số lệnh gia công'),
(N'派工单数',N'en',N'Dispatch count'),(N'派工单数',N'ja',N'派工伝票数'),(N'派工单数',N'ko',N'작업지시 수'),(N'派工单数',N'de',N'Dispositionen'),(N'派工单数',N'es',N'N.º asignaciones'),(N'派工单数',N'fr',N'Nb affectations'),(N'派工单数',N'ru',N'Кол-во нарядов'),(N'派工单数',N'th',N'จำนวนใบสั่งงาน'),(N'派工单数',N'vi',N'Số phiếu điều phối'),
(N'完工数量',N'en',N'Completed qty'),(N'完工数量',N'ja',N'完了数量'),(N'完工数量',N'ko',N'완료 수량'),(N'完工数量',N'de',N'Fertigmenge'),(N'完工数量',N'es',N'Cantidad completada'),(N'完工数量',N'fr',N'Qté terminée'),(N'完工数量',N'ru',N'Кол-во завершено'),(N'完工数量',N'th',N'ปริมาณที่เสร็จ'),(N'完工数量',N'vi',N'SL hoàn thành'),
(N'生产进度%',N'en',N'Progress %'),(N'生产进度%',N'ja',N'生産進捗%'),(N'生产进度%',N'ko',N'생산 진도 %'),(N'生产进度%',N'de',N'Produktionsfortschritt %'),(N'生产进度%',N'es',N'Progreso %'),(N'生产进度%',N'fr',N'Progression %'),(N'生产进度%',N'ru',N'Прогресс %'),(N'生产进度%',N'th',N'ความคืบหน้าการผลิต %'),(N'生产进度%',N'vi',N'Tiến độ sản xuất %'),
(N'经手人编码',N'en',N'Handler code'),(N'经手人编码',N'ja',N'担当者コード'),(N'经手人编码',N'ko',N'담당자 코드'),(N'经手人编码',N'de',N'Sachbearbeitercode'),(N'经手人编码',N'es',N'Código responsable'),(N'经手人编码',N'fr',N'Code responsable'),(N'经手人编码',N'ru',N'Код ответственного'),(N'经手人编码',N'th',N'รหัสผู้รับผิดชอบ'),(N'经手人编码',N'vi',N'Mã người xử lý'),
(N'领用人编码',N'en',N'Picker code'),(N'领用人编码',N'ja',N'受領者コード'),(N'领用人编码',N'ko',N'수령인 코드'),(N'领用人编码',N'de',N'Entnehmercode'),(N'领用人编码',N'es',N'Código receptor'),(N'领用人编码',N'fr',N'Code préleveur'),(N'领用人编码',N'ru',N'Код получателя'),(N'领用人编码',N'th',N'รหัสผู้รับ'),(N'领用人编码',N'vi',N'Mã người lĩnh'),
(N'生产车间编码',N'en',N'Workshop code'),(N'生产车间编码',N'ja',N'生産車間コード'),(N'生产车间编码',N'ko',N'생산작업장 코드'),(N'生产车间编码',N'de',N'Fertigungsbereichscode'),(N'生产车间编码',N'es',N'Código taller'),(N'生产车间编码',N'fr',N'Code atelier'),(N'生产车间编码',N'ru',N'Код цеха'),(N'生产车间编码',N'th',N'รหัสแผนกผลิต'),(N'生产车间编码',N'vi',N'Mã xưởng'),
(N'仓库编码',N'en',N'Warehouse code'),(N'仓库编码',N'ja',N'倉庫コード'),(N'仓库编码',N'ko',N'창고 코드'),(N'仓库编码',N'de',N'Lagercode'),(N'仓库编码',N'es',N'Código almacén'),(N'仓库编码',N'fr',N'Code entrepôt'),(N'仓库编码',N'ru',N'Код склада'),(N'仓库编码',N'th',N'รหัสคลังสินค้า'),(N'仓库编码',N'vi',N'Mã kho'),
(N'部门编码',N'en',N'Dept code'),(N'部门编码',N'ja',N'部門コード'),(N'部门编码',N'ko',N'부서 코드'),(N'部门编码',N'de',N'Abteilungscode'),(N'部门编码',N'es',N'Código departamento'),(N'部门编码',N'fr',N'Code département'),(N'部门编码',N'ru',N'Код отдела'),(N'部门编码',N'th',N'รหัสแผนก'),(N'部门编码',N'vi',N'Mã phòng ban'),
(N'存货编码',N'en',N'Inventory code'),(N'存货编码',N'ja',N'存貨コード'),(N'存货编码',N'ko',N'재고 코드'),(N'存货编码',N'de',N'Artikelcode'),(N'存货编码',N'es',N'Código artículo'),(N'存货编码',N'fr',N'Code article'),(N'存货编码',N'ru',N'Код номенклатуры'),(N'存货编码',N'th',N'รหัสสินค้า'),(N'存货编码',N'vi',N'Mã hàng tồn'),
(N'材料编码',N'en',N'Material code'),(N'材料编码',N'ja',N'材料コード'),(N'材料编码',N'ko',N'자재 코드'),(N'材料编码',N'de',N'Materialcode'),(N'材料编码',N'es',N'Código material'),(N'材料编码',N'fr',N'Code matériau'),(N'材料编码',N'ru',N'Код материала'),(N'材料编码',N'th',N'รหัสวัสดุ'),(N'材料编码',N'vi',N'Mã vật liệu'),
(N'明细.生产车间',N'en',N'Workshop (line)'),(N'明细.生产车间',N'ja',N'明細.生産車間'),(N'明细.生产车间',N'ko',N'명세.생산작업장'),(N'明细.生产车间',N'de',N'Position.Fertigungsbereich'),(N'明细.生产车间',N'es',N'Línea. Taller'),(N'明细.生产车间',N'fr',N'Ligne. Atelier'),(N'明细.生产车间',N'ru',N'Строка. Цех'),(N'明细.生产车间',N'th',N'รายการ.แผนกผลิต'),(N'明细.生产车间',N'vi',N'Dòng. Xưởng sản xuất'),
(N'工作中心',N'en',N'Work center'),(N'工作中心',N'ja',N'作業センター'),(N'工作中心',N'ko',N'작업장'),(N'工作中心',N'de',N'Arbeitsplatz'),(N'工作中心',N'es',N'Centro de trabajo'),(N'工作中心',N'fr',N'Centre de travail'),(N'工作中心',N'ru',N'Рабочий центр'),(N'工作中心',N'th',N'ศูนย์งาน'),(N'工作中心',N'vi',N'Tâm việc'),
(N'班组',N'en',N'Team'),(N'班组',N'ja',N'班組'),(N'班组',N'ko',N'반'),(N'班组',N'de',N'Schichtmannschaft'),(N'班组',N'es',N'Equipo'),(N'班组',N'fr',N'Équipe'),(N'班组',N'ru',N'Бригада'),(N'班组',N'th',N'ทีมงาน'),(N'班组',N'vi',N'Tổ'),
(N'工人',N'en',N'Worker'),(N'工人',N'ja',N'作業員'),(N'工人',N'ko',N'작업자'),(N'工人',N'de',N'Arbeiter'),(N'工人',N'es',N'Trabajador'),(N'工人',N'fr',N'Ouvrier'),(N'工人',N'ru',N'Рабочий'),(N'工人',N'th',N'คนงาน'),(N'工人',N'vi',N'Công nhân'),
(N'设备',N'en',N'Equipment'),(N'设备',N'ja',N'設備'),(N'设备',N'ko',N'설비'),(N'设备',N'de',N'Anlage'),(N'设备',N'es',N'Equipo'),(N'设备',N'fr',N'Équipement'),(N'设备',N'ru',N'Оборудование'),(N'设备',N'th',N'อุปกรณ์'),(N'设备',N'vi',N'Thiết bị'),
(N'入库单号',N'en',N'Receipt no.'),(N'入库单号',N'ja',N'入庫伝票番号'),(N'入库单号',N'ko',N'입고 전표 번호'),(N'入库单号',N'de',N'Eingangsbelegnr.'),(N'入库单号',N'es',N'N.º entrada'),(N'入库单号',N'fr',N'N° d''entrée'),(N'入库单号',N'ru',N'№ поступления'),(N'入库单号',N'th',N'เลขที่ใบรับเข้า'),(N'入库单号',N'vi',N'Số phiếu nhập'),
(N'来料客户',N'en',N'Source customer'),(N'来料客户',N'ja',N'着荷客先'),(N'来料客户',N'ko',N'입고 거래처'),(N'来料客户',N'de',N'Eingangskunde'),(N'来料客户',N'es',N'Cliente de entrada'),(N'来料客户',N'fr',N'Client d''entrée'),(N'来料客户',N'ru',N'Клиент-поставщик'),(N'来料客户',N'th',N'ลูกค้าที่ส่งเข้า'),(N'来料客户',N'vi',N'Khách hàng gửi đến'),
(N'销售单位',N'en',N'Sales UOM'),(N'销售单位',N'ja',N'販売単位'),(N'销售单位',N'ko',N'판매 단위'),(N'销售单位',N'de',N'Vertriebseinheit'),(N'销售单位',N'es',N'UM venta'),(N'销售单位',N'fr',N'UV'),(N'销售单位',N'ru',N'Ед. продаж'),(N'销售单位',N'th',N'หน่วยขาย'),(N'销售单位',N'vi',N'Đơn vị bán'),
(N'预计交货日期',N'en',N'Estimated delivery'),(N'预计交货日期',N'ja',N'納期'),(N'预计交货日期',N'ko',N'납기일'),(N'预计交货日期',N'de',N'Liefertermin'),(N'预计交货日期',N'es',N'Entrega prevista'),(N'预计交货日期',N'fr',N'Livraison prévue'),(N'预计交货日期',N'ru',N'Ожид. поставка'),(N'预计交货日期',N'th',N'วันกำหนดส่ง'),(N'预计交货日期',N'vi',N'Ngày giao dự kiến')
) AS s(ref_key,locale,text)
ON t.scope = 'field' AND t.ref_key = s.ref_key AND t.locale = s.locale
WHEN NOT MATCHED THEN INSERT (scope, ref_key, locale, text, source) VALUES ('field', s.ref_key, s.locale, s.text, 'manual');

-- label_en 通道回填(ADR-0001 label+label_en 协议;en 为主)
UPDATE f SET f.label_en = s.text
FROM yj_field f JOIN yj_translation s ON s.scope='field' AND s.ref_key=f.label AND s.locale='en'
WHERE (f.label_en IS NULL OR f.label_en = N'');

-- 面板名补录(scope='panel',§3.1 新增面板必须同步译名;后期注册的报表面板遗漏项)
MERGE yj_translation AS t USING (VALUES
(N'销售订单',N'en',N'Sales Order'),(N'销售订单',N'ja',N'受注伝票'),(N'销售订单',N'ko',N'수주 오더'),(N'销售订单',N'de',N'Kundenauftrag'),(N'销售订单',N'es',N'Pedido de venta'),(N'销售订单',N'fr',N'Commande de vente'),(N'销售订单',N'ru',N'Заказ клиента'),(N'销售订单',N'th',N'ใบสั่งขาย'),(N'销售订单',N'vi',N'Đơn hàng bán'),
(N'销售订单明细表',N'en',N'Sales Order Details'),(N'销售订单明细表',N'ja',N'受注伝票明細'),(N'销售订单明细表',N'ko',N'수주 오더 명세'),(N'销售订单明细表',N'de',N'Kundenauftragspositionen'),(N'销售订单明细表',N'es',N'Detalle pedidos de venta'),(N'销售订单明细表',N'fr',N'Détail commandes de vente'),(N'销售订单明细表',N'ru',N'Детали заказов клиентов'),(N'销售订单明细表',N'th',N'รายละเอียดใบสั่งขาย'),(N'销售订单明细表',N'vi',N'Chi tiết đơn hàng bán'),
(N'销售订单统计表',N'en',N'Sales Order Statistics'),(N'销售订单统计表',N'ja',N'受注統計表'),(N'销售订单统计表',N'ko',N'수주 통계표'),(N'销售订单统计表',N'de',N'Kundenauftragsstatistik'),(N'销售订单统计表',N'es',N'Estadística pedidos de venta'),(N'销售订单统计表',N'fr',N'Statistiques commandes de vente'),(N'销售订单统计表',N'ru',N'Статистика заказов'),(N'销售订单统计表',N'th',N'สถิติใบสั่งขาย'),(N'销售订单统计表',N'vi',N'Thống kê đơn hàng bán'),
(N'委外入库单明细表',N'en',N'Outsourcing Receipt Details'),(N'委外入库单明细表',N'ja',N'委託入庫明細'),(N'委外入库单明细表',N'ko',N'외주 입고 명세'),(N'委外入库单明细表',N'de',N'Fremdvergabe-Eingangsdetails'),(N'委外入库单明细表',N'es',N'Detalle entradas subcontratación'),(N'委外入库单明细表',N'fr',N'Détail entrées sous-traitance'),(N'委外入库单明细表',N'ru',N'Детали поступлений давальца'),(N'委外入库单明细表',N'th',N'รายละเอียดรับเข้างานผู้รับจ้าง'),(N'委外入库单明细表',N'vi',N'Chi tiết nhập gia công'),
(N'委外入库单统计表',N'en',N'Outsourcing Receipt Statistics'),(N'委外入库单统计表',N'ja',N'委託入庫統計表'),(N'委外入库单统计表',N'ko',N'외주 입고 통계표'),(N'委外入库单统计表',N'de',N'Fremdvergabe-Eingangsstatistik'),(N'委外入库单统计表',N'es',N'Estadística entradas subcontratación'),(N'委外入库单统计表',N'fr',N'Statistiques entrées sous-traitance'),(N'委外入库单统计表',N'ru',N'Статистика поступлений давальца'),(N'委外入库单统计表',N'th',N'สถิติรับเข้างานผู้รับจ้าง'),(N'委外入库单统计表',N'vi',N'Thống kê nhập gia công'),
(N'委外发料单明细表',N'en',N'Outsourcing Issue Details'),(N'委外发料单明细表',N'ja',N'委託払出明細'),(N'委外发料单明细表',N'ko',N'외주 지급 명세'),(N'委外发料单明细表',N'de',N'Fremdvergabe-Ausgabedetails'),(N'委外发料单明细表',N'es',N'Detalle emisiones subcontratación'),(N'委外发料单明细表',N'fr',N'Détail sorties sous-traitance'),(N'委外发料单明细表',N'ru',N'Детали выдачи давальцу'),(N'委外发料单明细表',N'th',N'รายละเอียดเบิกจ่ายงานผู้รับจ้าง'),(N'委外发料单明细表',N'vi',N'Chi tiết cấp liệu gia công'),
(N'委外发料单统计表',N'en',N'Outsourcing Issue Statistics'),(N'委外发料单统计表',N'ja',N'委託払出統計表'),(N'委外发料单统计表',N'ko',N'외주 지급 통계표'),(N'委外发料单统计表',N'de',N'Fremdvergabe-Ausgabestatistik'),(N'委外发料单统计表',N'es',N'Estadística emisiones subcontratación'),(N'委外发料单统计表',N'fr',N'Statistiques sorties sous-traitance'),(N'委外发料单统计表',N'ru',N'Статистика выдач давальцу'),(N'委外发料单统计表',N'th',N'สถิติเบิกจ่ายงานผู้รับจ้าง'),(N'委外发料单统计表',N'vi',N'Thống kê cấp liệu gia công'),
(N'工序派工单明细表',N'en',N'Process Dispatch Details'),(N'工序派工单明细表',N'ja',N'工程派工明細'),(N'工序派工单明细表',N'ko',N'공정 작업지시 명세'),(N'工序派工单明细表',N'de',N'Arbeitsgang-Dispositionsdaten'),(N'工序派工单明细表',N'es',N'Detalle asignaciones de proceso'),(N'工序派工单明细表',N'fr',N'Détail affectations de process'),(N'工序派工单明细表',N'ru',N'Детали нарядов по операциям'),(N'工序派工单明细表',N'th',N'รายละเอียดจัดสรรงาน'),(N'工序派工单明细表',N'vi',N'Chi tiết điều phối công đoạn'),
(N'工序派工单统计表',N'en',N'Process Dispatch Statistics'),(N'工序派工单统计表',N'ja',N'工程派工統計表'),(N'工序派工单统计表',N'ko',N'공정 작업지시 통계표'),(N'工序派工单统计表',N'de',N'Arbeitsgang-Dispositionsstatistik'),(N'工序派工单统计表',N'es',N'Estadística asignaciones de proceso'),(N'工序派工单统计表',N'fr',N'Statistiques affectations de process'),(N'工序派工单统计表',N'ru',N'Статистика нарядов по операциям'),(N'工序派工单统计表',N'th',N'สถิติจัดสรรงาน'),(N'工序派工单统计表',N'vi',N'Thống kê điều phối công đoạn')
) AS s(ref_key,locale,text)
ON t.scope = 'panel' AND t.ref_key = s.ref_key AND t.locale = s.locale
WHEN NOT MATCHED THEN INSERT (scope, ref_key, locale, text, source) VALUES ('panel', s.ref_key, s.locale, s.text, 'manual');

-- 面板名通道回填(yj_panel.panel_name_en)
UPDATE p SET p.panel_name_en = s.text
FROM yj_panel p JOIN yj_translation s ON s.scope='panel' AND s.ref_key=p.panel_name AND s.locale='en'
WHERE (p.panel_name_en IS NULL OR p.panel_name_en = N'');

PRINT N'i18n-replica-labels 完成';
