-- migrate-phase23-forms-batch2.sql — 剩余 24 张工序单据面板(混料8+成型5+组装6+品质2+跨工序3)
SET NOCOUNT ON;
GO
-- ═══ 混料工序(8张) ═══
IF OBJECT_ID('pr_mix_process') IS NULL CREATE TABLE pr_mix_process (id INT IDENTITY PRIMARY KEY, 单据编号 NVARCHAR(50) NOT NULL, 单据日期 DATE, 型号 NVARCHAR(50), 工序步骤 NVARCHAR(200), 参数要求 NVARCHAR(200), 实测值 NVARCHAR(100), 判定 NVARCHAR(20), 操作人 NVARCHAR(50), 备注 NVARCHAR(500), asp_user1 NVARCHAR(50), asp_time1 DATETIME2 DEFAULT GETDATE(), asp_cancel CHAR(1) DEFAULT 'N');
IF NOT EXISTS (SELECT 1 FROM yj_panel WHERE panel_code='PR_MIX_PROCESS') INSERT INTO yj_panel (panel_code,panel_name,category,mode,line_table,head_table,group_col,pk_col,prefix,date_col,module_group) VALUES ('PR_MIX_PROCESS',N'阻垢工序控制',N'单据','doc','pr_mix_process','pr_mix_process','单据编号','id','PMP','单据日期',N'生产制造');
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='PR_MIX_PROCESS' AND place='header') INSERT INTO yj_field (panel_code,col_name,label,data_type,place,seq,width,editable,required) VALUES ('PR_MIX_PROCESS','单据编号',N'单据编号','文本','header',1,140,0,1),('PR_MIX_PROCESS','单据日期',N'单据日期','日期','header',2,120,1,1),('PR_MIX_PROCESS','型号',N'型号','文本','header',3,100,1,0),('PR_MIX_PROCESS','工序步骤',N'工序步骤','文本','header',4,200,1,0),('PR_MIX_PROCESS','参数要求',N'参数要求','文本','header',5,200,1,0),('PR_MIX_PROCESS','实测值',N'实测值','文本','header',6,100,1,0),('PR_MIX_PROCESS','判定',N'判定','下拉框','header',7,80,1,0),('PR_MIX_PROCESS','操作人',N'操作人','文本','header',8,100,1,0),('PR_MIX_PROCESS','备注',N'备注','文本','header',9,200,1,0);
GO
IF OBJECT_ID('pr_mix_feed') IS NULL CREATE TABLE pr_mix_feed (id INT IDENTITY PRIMARY KEY, 单据编号 NVARCHAR(50) NOT NULL, 单据日期 DATE, 物料名称 NVARCHAR(100), 批号 NVARCHAR(50), 投料量 DECIMAL(18,4), 投料人 NVARCHAR(50), 复核人 NVARCHAR(50), 备注 NVARCHAR(500), asp_user1 NVARCHAR(50), asp_time1 DATETIME2 DEFAULT GETDATE(), asp_cancel CHAR(1) DEFAULT 'N');
IF NOT EXISTS (SELECT 1 FROM yj_panel WHERE panel_code='PR_MIX_FEED') INSERT INTO yj_panel (panel_code,panel_name,category,mode,line_table,head_table,group_col,pk_col,prefix,date_col,module_group) VALUES ('PR_MIX_FEED',N'阻垢投料单',N'单据','doc','pr_mix_feed','pr_mix_feed','单据编号','id','PMF','单据日期',N'生产制造');
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='PR_MIX_FEED' AND place='header') INSERT INTO yj_field (panel_code,col_name,label,data_type,place,seq,width,editable,required) VALUES ('PR_MIX_FEED','单据编号',N'单据编号','文本','header',1,140,0,1),('PR_MIX_FEED','单据日期',N'单据日期','日期','header',2,120,1,1),('PR_MIX_FEED','物料名称',N'物料名称','文本','header',3,160,1,0),('PR_MIX_FEED','批号',N'批号','文本','header',4,120,1,0),('PR_MIX_FEED','投料量',N'投料量(kg)','小数','header',5,110,1,0),('PR_MIX_FEED','投料人',N'投料人','文本','header',6,100,1,0),('PR_MIX_FEED','复核人',N'复核人','文本','header',7,100,1,0),('PR_MIX_FEED','备注',N'备注','文本','header',8,200,1,0);
GO
IF OBJECT_ID('pr_mix_granule') IS NULL CREATE TABLE pr_mix_granule (id INT IDENTITY PRIMARY KEY, 单据编号 NVARCHAR(50) NOT NULL, 单据日期 DATE, 型号 NVARCHAR(50), 模孔孔径 NVARCHAR(50), 加热温度 NVARCHAR(50), 主机转速 NVARCHAR(50), 粒度 NVARCHAR(50), 判定 NVARCHAR(20), 操作人 NVARCHAR(50), 备注 NVARCHAR(500), asp_user1 NVARCHAR(50), asp_time1 DATETIME2 DEFAULT GETDATE(), asp_cancel CHAR(1) DEFAULT 'N');
IF NOT EXISTS (SELECT 1 FROM yj_panel WHERE panel_code='PR_MIX_GRANULE') INSERT INTO yj_panel (panel_code,panel_name,category,mode,line_table,head_table,group_col,pk_col,prefix,date_col,module_group) VALUES ('PR_MIX_GRANULE',N'造粒过程控制',N'单据','doc','pr_mix_granule','pr_mix_granule','单据编号','id','PMG','单据日期',N'生产制造');
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='PR_MIX_GRANULE' AND place='header') INSERT INTO yj_field (panel_code,col_name,label,data_type,place,seq,width,editable,required) VALUES ('PR_MIX_GRANULE','单据编号',N'单据编号','文本','header',1,140,0,1),('PR_MIX_GRANULE','单据日期',N'单据日期','日期','header',2,120,1,1),('PR_MIX_GRANULE','型号',N'型号','文本','header',3,100,1,0),('PR_MIX_GRANULE','模孔孔径',N'模孔孔径(mm)','文本','header',4,110,1,0),('PR_MIX_GRANULE','加热温度',N'加热温度(℃)','文本','header',5,110,1,0),('PR_MIX_GRANULE','主机转速',N'主机转速(rpm)','文本','header',6,110,1,0),('PR_MIX_GRANULE','粒度',N'粒度','文本','header',7,100,1,0),('PR_MIX_GRANULE','判定',N'判定','下拉框','header',8,80,1,0),('PR_MIX_GRANULE','操作人',N'操作人','文本','header',9,100,1,0),('PR_MIX_GRANULE','备注',N'备注','文本','header',10,200,1,0);
GO
IF OBJECT_ID('pr_mix_blend') IS NULL CREATE TABLE pr_mix_blend (id INT IDENTITY PRIMARY KEY, 单据编号 NVARCHAR(50) NOT NULL, 单据日期 DATE, 混合批次 NVARCHAR(50), 混合时间_min INT, 设备编号 NVARCHAR(50), 物料清单 NVARCHAR(500), 混合人 NVARCHAR(50), 备注 NVARCHAR(500), asp_user1 NVARCHAR(50), asp_time1 DATETIME2 DEFAULT GETDATE(), asp_cancel CHAR(1) DEFAULT 'N');
IF NOT EXISTS (SELECT 1 FROM yj_panel WHERE panel_code='PR_MIX_BLEND') INSERT INTO yj_panel (panel_code,panel_name,category,mode,line_table,head_table,group_col,pk_col,prefix,date_col,module_group) VALUES ('PR_MIX_BLEND',N'物料混合记录',N'单据','doc','pr_mix_blend','pr_mix_blend','单据编号','id','PMB','单据日期',N'生产制造');
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='PR_MIX_BLEND' AND place='header') INSERT INTO yj_field (panel_code,col_name,label,data_type,place,seq,width,editable,required) VALUES ('PR_MIX_BLEND','单据编号',N'单据编号','文本','header',1,140,0,1),('PR_MIX_BLEND','单据日期',N'单据日期','日期','header',2,120,1,1),('PR_MIX_BLEND','混合批次',N'混合批次','文本','header',3,120,1,0),('PR_MIX_BLEND','混合时间_min',N'混合时间(min)','整数','header',4,110,1,0),('PR_MIX_BLEND','设备编号',N'设备编号','文本','header',5,100,1,0),('PR_MIX_BLEND','物料清单',N'物料清单','文本','header',6,300,1,0),('PR_MIX_BLEND','混合人',N'混合人','文本','header',7,100,1,0),('PR_MIX_BLEND','备注',N'备注','文本','header',8,200,1,0);
GO
IF OBJECT_ID('pr_mix_check') IS NULL CREATE TABLE pr_mix_check (id INT IDENTITY PRIMARY KEY, 单据编号 NVARCHAR(50) NOT NULL, 单据日期 DATE, 设备名称 NVARCHAR(100), 点检项目 NVARCHAR(200), 标准值 NVARCHAR(100), 实测值 NVARCHAR(100), 判定 NVARCHAR(20), 点检人 NVARCHAR(50), 备注 NVARCHAR(500), asp_user1 NVARCHAR(50), asp_time1 DATETIME2 DEFAULT GETDATE(), asp_cancel CHAR(1) DEFAULT 'N');
IF NOT EXISTS (SELECT 1 FROM yj_panel WHERE panel_code='PR_MIX_CHECK') INSERT INTO yj_panel (panel_code,panel_name,category,mode,line_table,head_table,group_col,pk_col,prefix,date_col,module_group) VALUES ('PR_MIX_CHECK',N'设备点检表',N'单据','doc','pr_mix_check','pr_mix_check','单据编号','id','PMC','单据日期',N'生产制造');
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='PR_MIX_CHECK' AND place='header') INSERT INTO yj_field (panel_code,col_name,label,data_type,place,seq,width,editable,required) VALUES ('PR_MIX_CHECK','单据编号',N'单据编号','文本','header',1,140,0,1),('PR_MIX_CHECK','单据日期',N'单据日期','日期','header',2,120,1,1),('PR_MIX_CHECK','设备名称',N'设备名称','文本','header',3,150,1,0),('PR_MIX_CHECK','点检项目',N'点检项目','文本','header',4,200,1,0),('PR_MIX_CHECK','标准值',N'标准值','文本','header',5,100,1,0),('PR_MIX_CHECK','实测值',N'实测值','文本','header',6,100,1,0),('PR_MIX_CHECK','判定',N'判定','下拉框','header',7,80,1,0),('PR_MIX_CHECK','点检人',N'点检人','文本','header',8,100,1,0),('PR_MIX_CHECK','备注',N'备注','文本','header',9,200,1,0);
GO
IF OBJECT_ID('pr_mix_daily') IS NULL CREATE TABLE pr_mix_daily (id INT IDENTITY PRIMARY KEY, 单据编号 NVARCHAR(50) NOT NULL, 单据日期 DATE, 班次 NVARCHAR(10), 型号 NVARCHAR(50), 计划产量 DECIMAL(18,2), 实际产量 DECIMAL(18,2), 合格数量 DECIMAL(18,2), 不良数量 DECIMAL(18,2), 操作工 NVARCHAR(50), 备注 NVARCHAR(500), asp_user1 NVARCHAR(50), asp_time1 DATETIME2 DEFAULT GETDATE(), asp_cancel CHAR(1) DEFAULT 'N');
IF NOT EXISTS (SELECT 1 FROM yj_panel WHERE panel_code='PR_MIX_DAILY') INSERT INTO yj_panel (panel_code,panel_name,category,mode,line_table,head_table,group_col,pk_col,prefix,date_col,module_group) VALUES ('PR_MIX_DAILY',N'混料日报表',N'单据','doc','pr_mix_daily','pr_mix_daily','单据编号','id','PMD','单据日期',N'生产制造');
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='PR_MIX_DAILY' AND place='header') INSERT INTO yj_field (panel_code,col_name,label,data_type,place,seq,width,editable,required) VALUES ('PR_MIX_DAILY','单据编号',N'单据编号','文本','header',1,140,0,1),('PR_MIX_DAILY','单据日期',N'单据日期','日期','header',2,120,1,1),('PR_MIX_DAILY','班次',N'班次','下拉框','header',3,80,1,0),('PR_MIX_DAILY','型号',N'型号','文本','header',4,100,1,0),('PR_MIX_DAILY','计划产量',N'计划产量','小数','header',5,100,1,0),('PR_MIX_DAILY','实际产量',N'实际产量','小数','header',6,100,1,0),('PR_MIX_DAILY','合格数量',N'合格数量','小数','header',7,100,1,0),('PR_MIX_DAILY','不良数量',N'不良数量','小数','header',8,100,1,0),('PR_MIX_DAILY','操作工',N'操作工','文本','header',9,100,1,0),('PR_MIX_DAILY','备注',N'备注','文本','header',10,200,1,0);
GO
-- ═══ 成型工序(5张) ═══
IF OBJECT_ID('pr_sinter_qc') IS NULL CREATE TABLE pr_sinter_qc (id INT IDENTITY PRIMARY KEY, 单据编号 NVARCHAR(50) NOT NULL, 单据日期 DATE, 工单号 NVARCHAR(50), 炉温设定 NVARCHAR(50), 炉温实测 NVARCHAR(50), 烧结时间_min INT, 炭棒长度 DECIMAL(18,2), 炭棒外径 DECIMAL(18,2), 炭棒重量 DECIMAL(18,2), 外观判定 NVARCHAR(20), 检验人 NVARCHAR(50), 备注 NVARCHAR(500), asp_user1 NVARCHAR(50), asp_time1 DATETIME2 DEFAULT GETDATE(), asp_cancel CHAR(1) DEFAULT 'N');
IF NOT EXISTS (SELECT 1 FROM yj_panel WHERE panel_code='PR_SINTER_QC') INSERT INTO yj_panel (panel_code,panel_name,category,mode,line_table,head_table,group_col,pk_col,prefix,date_col,module_group) VALUES ('PR_SINTER_QC',N'烧结制程检验',N'单据','doc','pr_sinter_qc','pr_sinter_qc','单据编号','id','PSQ','单据日期',N'生产制造');
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='PR_SINTER_QC' AND place='header') INSERT INTO yj_field (panel_code,col_name,label,data_type,place,seq,width,editable,required) VALUES ('PR_SINTER_QC','单据编号',N'单据编号','文本','header',1,140,0,1),('PR_SINTER_QC','单据日期',N'单据日期','日期','header',2,120,1,1),('PR_SINTER_QC','工单号',N'工单号','文本','header',3,130,1,0),('PR_SINTER_QC','炉温设定',N'炉温设定(℃)','文本','header',4,110,1,0),('PR_SINTER_QC','炉温实测',N'炉温实测(℃)','文本','header',5,110,1,0),('PR_SINTER_QC','烧结时间_min',N'烧结时间(min)','整数','header',6,110,1,0),('PR_SINTER_QC','炭棒长度',N'炭棒长度(mm)','小数','header',7,110,1,0),('PR_SINTER_QC','炭棒外径',N'炭棒外径(mm)','小数','header',8,110,1,0),('PR_SINTER_QC','炭棒重量',N'炭棒重量(g)','小数','header',9,110,1,0),('PR_SINTER_QC','外观判定',N'外观判定','下拉框','header',10,90,1,0),('PR_SINTER_QC','检验人',N'检验人','文本','header',11,100,1,0),('PR_SINTER_QC','备注',N'备注','文本','header',12,200,1,0);
GO
IF OBJECT_ID('pr_form_daily') IS NULL CREATE TABLE pr_form_daily (id INT IDENTITY PRIMARY KEY, 单据编号 NVARCHAR(50) NOT NULL, 单据日期 DATE, 工单号 NVARCHAR(50), 班次 NVARCHAR(10), 产品名称 NVARCHAR(100), 计划数量 DECIMAL(18,2), 成型数量 DECIMAL(18,2), 合格数量 DECIMAL(18,2), 不良数量 DECIMAL(18,2), 操作工 NVARCHAR(50), 备注 NVARCHAR(500), asp_user1 NVARCHAR(50), asp_time1 DATETIME2 DEFAULT GETDATE(), asp_cancel CHAR(1) DEFAULT 'N');
IF NOT EXISTS (SELECT 1 FROM yj_panel WHERE panel_code='PR_FORM_DAILY') INSERT INTO yj_panel (panel_code,panel_name,category,mode,line_table,head_table,group_col,pk_col,prefix,date_col,module_group) VALUES ('PR_FORM_DAILY',N'成型日报表',N'单据','doc','pr_form_daily','pr_form_daily','单据编号','id','PFD','单据日期',N'生产制造');
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='PR_FORM_DAILY' AND place='header') INSERT INTO yj_field (panel_code,col_name,label,data_type,place,seq,width,editable,required) VALUES ('PR_FORM_DAILY','单据编号',N'单据编号','文本','header',1,140,0,1),('PR_FORM_DAILY','单据日期',N'单据日期','日期','header',2,120,1,1),('PR_FORM_DAILY','工单号',N'工单号','文本','header',3,130,1,0),('PR_FORM_DAILY','班次',N'班次','下拉框','header',4,80,1,0),('PR_FORM_DAILY','产品名称',N'产品名称','文本','header',5,160,1,0),('PR_FORM_DAILY','计划数量',N'计划数量','小数','header',6,100,1,0),('PR_FORM_DAILY','成型数量',N'成型数量','小数','header',7,100,1,0),('PR_FORM_DAILY','合格数量',N'合格数量','小数','header',8,100,1,0),('PR_FORM_DAILY','不良数量',N'不良数量','小数','header',9,100,1,0),('PR_FORM_DAILY','操作工',N'操作工','文本','header',10,100,1,0),('PR_FORM_DAILY','备注',N'备注','文本','header',11,200,1,0);
GO
IF OBJECT_ID('pr_demold_qc') IS NULL CREATE TABLE pr_demold_qc (id INT IDENTITY PRIMARY KEY, 单据编号 NVARCHAR(50) NOT NULL, 单据日期 DATE, 工单号 NVARCHAR(50), 模具编号 NVARCHAR(50), 脱模数量 INT, 长度合格 INT, 外观合格 INT, 不良数量 INT, 巡检人 NVARCHAR(50), 备注 NVARCHAR(500), asp_user1 NVARCHAR(50), asp_time1 DATETIME2 DEFAULT GETDATE(), asp_cancel CHAR(1) DEFAULT 'N');
IF NOT EXISTS (SELECT 1 FROM yj_panel WHERE panel_code='PR_DEMOLD_QC') INSERT INTO yj_panel (panel_code,panel_name,category,mode,line_table,head_table,group_col,pk_col,prefix,date_col,module_group) VALUES ('PR_DEMOLD_QC',N'脱模检验记录',N'单据','doc','pr_demold_qc','pr_demold_qc','单据编号','id','PDQ','单据日期',N'生产制造');
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='PR_DEMOLD_QC' AND place='header') INSERT INTO yj_field (panel_code,col_name,label,data_type,place,seq,width,editable,required) VALUES ('PR_DEMOLD_QC','单据编号',N'单据编号','文本','header',1,140,0,1),('PR_DEMOLD_QC','单据日期',N'单据日期','日期','header',2,120,1,1),('PR_DEMOLD_QC','工单号',N'工单号','文本','header',3,130,1,0),('PR_DEMOLD_QC','模具编号',N'模具编号','文本','header',4,110,1,0),('PR_DEMOLD_QC','脱模数量',N'脱模数量','整数','header',5,100,1,0),('PR_DEMOLD_QC','长度合格',N'长度合格','整数','header',6,100,1,0),('PR_DEMOLD_QC','外观合格',N'外观合格','整数','header',7,100,1,0),('PR_DEMOLD_QC','不良数量',N'不良数量','整数','header',8,100,1,0),('PR_DEMOLD_QC','巡检人',N'巡检人','文本','header',9,100,1,0),('PR_DEMOLD_QC','备注',N'备注','文本','header',10,200,1,0);
GO
IF OBJECT_ID('pr_efficiency') IS NULL CREATE TABLE pr_efficiency (id INT IDENTITY PRIMARY KEY, 单据编号 NVARCHAR(50) NOT NULL, 单据日期 DATE, 班次 NVARCHAR(10), 人数 INT, 产量 DECIMAL(18,2), 人均效率 DECIMAL(18,2), 备注 NVARCHAR(500), asp_user1 NVARCHAR(50), asp_time1 DATETIME2 DEFAULT GETDATE(), asp_cancel CHAR(1) DEFAULT 'N');
IF NOT EXISTS (SELECT 1 FROM yj_panel WHERE panel_code='PR_EFFICIENCY') INSERT INTO yj_panel (panel_code,panel_name,category,mode,line_table,head_table,group_col,pk_col,prefix,date_col,module_group) VALUES ('PR_EFFICIENCY',N'人均效率表',N'单据','doc','pr_efficiency','pr_efficiency','单据编号','id','PEF','单据日期',N'生产制造');
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='PR_EFFICIENCY' AND place='header') INSERT INTO yj_field (panel_code,col_name,label,data_type,place,seq,width,editable,required) VALUES ('PR_EFFICIENCY','单据编号',N'单据编号','文本','header',1,140,0,1),('PR_EFFICIENCY','单据日期',N'单据日期','日期','header',2,120,1,1),('PR_EFFICIENCY','班次',N'班次','下拉框','header',3,80,1,0),('PR_EFFICIENCY','人数',N'人数','整数','header',4,80,1,0),('PR_EFFICIENCY','产量',N'产量','小数','header',5,100,1,0),('PR_EFFICIENCY','人均效率',N'人均效率','小数','header',6,100,1,0),('PR_EFFICIENCY','备注',N'备注','文本','header',7,200,1,0);
GO
IF OBJECT_ID('pr_qc_control') IS NULL CREATE TABLE pr_qc_control (id INT IDENTITY PRIMARY KEY, 单据编号 NVARCHAR(50) NOT NULL, 单据日期 DATE, 产品类型 NVARCHAR(100), 管控点 NVARCHAR(200), 控制要求 NVARCHAR(500), 检验方法 NVARCHAR(200), 检验频率 NVARCHAR(50), 备注 NVARCHAR(500), asp_user1 NVARCHAR(50), asp_time1 DATETIME2 DEFAULT GETDATE(), asp_cancel CHAR(1) DEFAULT 'N');
IF NOT EXISTS (SELECT 1 FROM yj_panel WHERE panel_code='PR_QC_CONTROL') INSERT INTO yj_panel (panel_code,panel_name,category,mode,line_table,head_table,group_col,pk_col,prefix,date_col,module_group) VALUES ('PR_QC_CONTROL',N'品质管控点要求',N'单据','doc','pr_qc_control','pr_qc_control','单据编号','id','PQC','单据日期',N'生产制造');
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='PR_QC_CONTROL' AND place='header') INSERT INTO yj_field (panel_code,col_name,label,data_type,place,seq,width,editable,required) VALUES ('PR_QC_CONTROL','单据编号',N'单据编号','文本','header',1,140,0,1),('PR_QC_CONTROL','单据日期',N'单据日期','日期','header',2,120,1,1),('PR_QC_CONTROL','产品类型',N'产品类型','文本','header',3,150,1,0),('PR_QC_CONTROL','管控点',N'管控点','文本','header',4,200,1,0),('PR_QC_CONTROL','控制要求',N'控制要求','文本','header',5,300,1,0),('PR_QC_CONTROL','检验方法',N'检验方法','文本','header',6,200,1,0),('PR_QC_CONTROL','检验频率',N'检验频率','文本','header',7,100,1,0),('PR_QC_CONTROL','备注',N'备注','文本','header',8,200,1,0);
GO
-- ═══ 组装工序(6张) ═══
IF OBJECT_ID('pr_asm_return') IS NULL CREATE TABLE pr_asm_return (id INT IDENTITY PRIMARY KEY, 单据编号 NVARCHAR(50) NOT NULL, 单据日期 DATE, 炭棒批号 NVARCHAR(50), 不良类型 NVARCHAR(100), 不良数量 INT, 退货原因 NVARCHAR(500), 处理方式 NVARCHAR(100), 经办人 NVARCHAR(50), 备注 NVARCHAR(500), asp_user1 NVARCHAR(50), asp_time1 DATETIME2 DEFAULT GETDATE(), asp_cancel CHAR(1) DEFAULT 'N');
IF NOT EXISTS (SELECT 1 FROM yj_panel WHERE panel_code='PR_ASM_RETURN') INSERT INTO yj_panel (panel_code,panel_name,category,mode,line_table,head_table,group_col,pk_col,prefix,date_col,module_group) VALUES ('PR_ASM_RETURN',N'不良退货记录',N'单据','doc','pr_asm_return','pr_asm_return','单据编号','id','PAR','单据日期',N'生产制造');
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='PR_ASM_RETURN' AND place='header') INSERT INTO yj_field (panel_code,col_name,label,data_type,place,seq,width,editable,required) VALUES ('PR_ASM_RETURN','单据编号',N'单据编号','文本','header',1,140,0,1),('PR_ASM_RETURN','单据日期',N'单据日期','日期','header',2,120,1,1),('PR_ASM_RETURN','炭棒批号',N'炭棒批号','文本','header',3,120,1,0),('PR_ASM_RETURN','不良类型',N'不良类型','文本','header',4,150,1,0),('PR_ASM_RETURN','不良数量',N'不良数量','整数','header',5,100,1,0),('PR_ASM_RETURN','退货原因',N'退货原因','文本','header',6,300,1,0),('PR_ASM_RETURN','处理方式',N'处理方式','文本','header',7,120,1,0),('PR_ASM_RETURN','经办人',N'经办人','文本','header',8,100,1,0),('PR_ASM_RETURN','备注',N'备注','文本','header',9,200,1,0);
GO
IF OBJECT_ID('pr_mat_inspect') IS NULL CREATE TABLE pr_mat_inspect (id INT IDENTITY PRIMARY KEY, 单据编号 NVARCHAR(50) NOT NULL, 单据日期 DATE, 物料名称 NVARCHAR(100), 批号 NVARCHAR(50), 供应商 NVARCHAR(100), 抽检数量 INT, 合格数量 INT, 不良描述 NVARCHAR(500), 判定 NVARCHAR(20), 检查人 NVARCHAR(50), 备注 NVARCHAR(500), asp_user1 NVARCHAR(50), asp_time1 DATETIME2 DEFAULT GETDATE(), asp_cancel CHAR(1) DEFAULT 'N');
IF NOT EXISTS (SELECT 1 FROM yj_panel WHERE panel_code='PR_MAT_INSPECT') INSERT INTO yj_panel (panel_code,panel_name,category,mode,line_table,head_table,group_col,pk_col,prefix,date_col,module_group) VALUES ('PR_MAT_INSPECT',N'材料进厂检查',N'单据','doc','pr_mat_inspect','pr_mat_inspect','单据编号','id','PMI','单据日期',N'生产制造');
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='PR_MAT_INSPECT' AND place='header') INSERT INTO yj_field (panel_code,col_name,label,data_type,place,seq,width,editable,required) VALUES ('PR_MAT_INSPECT','单据编号',N'单据编号','文本','header',1,140,0,1),('PR_MAT_INSPECT','单据日期',N'单据日期','日期','header',2,120,1,1),('PR_MAT_INSPECT','物料名称',N'物料名称','文本','header',3,160,1,0),('PR_MAT_INSPECT','批号',N'批号','文本','header',4,120,1,0),('PR_MAT_INSPECT','供应商',N'供应商','文本','header',5,150,1,0),('PR_MAT_INSPECT','抽检数量',N'抽检数量','整数','header',6,100,1,0),('PR_MAT_INSPECT','合格数量',N'合格数量','整数','header',7,100,1,0),('PR_MAT_INSPECT','不良描述',N'不良描述','文本','header',8,300,1,0),('PR_MAT_INSPECT','判定',N'判定','下拉框','header',9,90,1,0),('PR_MAT_INSPECT','检查人',N'检查人','文本','header',10,100,1,0),('PR_MAT_INSPECT','备注',N'备注','文本','header',11,200,1,0);
GO
IF OBJECT_ID('pr_no_black') IS NULL CREATE TABLE pr_no_black (id INT IDENTITY PRIMARY KEY, 单据编号 NVARCHAR(50) NOT NULL, 单据日期 DATE, 工单号 NVARCHAR(50), 炭棒批号 NVARCHAR(50), 处理数量 INT, 处理时间_h DECIMAL(4,1), 处理结果 NVARCHAR(200), 操作人 NVARCHAR(50), 备注 NVARCHAR(500), asp_user1 NVARCHAR(50), asp_time1 DATETIME2 DEFAULT GETDATE(), asp_cancel CHAR(1) DEFAULT 'N');
IF NOT EXISTS (SELECT 1 FROM yj_panel WHERE panel_code='PR_NO_BLACK') INSERT INTO yj_panel (panel_code,panel_name,category,mode,line_table,head_table,group_col,pk_col,prefix,date_col,module_group) VALUES ('PR_NO_BLACK',N'无黑处理登记',N'单据','doc','pr_no_black','pr_no_black','单据编号','id','PNB','单据日期',N'生产制造');
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='PR_NO_BLACK' AND place='header') INSERT INTO yj_field (panel_code,col_name,label,data_type,place,seq,width,editable,required) VALUES ('PR_NO_BLACK','单据编号',N'单据编号','文本','header',1,140,0,1),('PR_NO_BLACK','单据日期',N'单据日期','日期','header',2,120,1,1),('PR_NO_BLACK','工单号',N'工单号','文本','header',3,130,1,0),('PR_NO_BLACK','炭棒批号',N'炭棒批号','文本','header',4,120,1,0),('PR_NO_BLACK','处理数量',N'处理数量','整数','header',5,100,1,0),('PR_NO_BLACK','处理时间_h',N'处理时间(h)','小数','header',6,110,1,0),('PR_NO_BLACK','处理结果',N'处理结果','文本','header',7,200,1,0),('PR_NO_BLACK','操作人',N'操作人','文本','header',8,100,1,0),('PR_NO_BLACK','备注',N'备注','文本','header',9,200,1,0);
GO
IF OBJECT_ID('pr_black_test') IS NULL CREATE TABLE pr_black_test (id INT IDENTITY PRIMARY KEY, 单据编号 NVARCHAR(50) NOT NULL, 单据日期 DATE, 工单号 NVARCHAR(50), 炭棒批号 NVARCHAR(50), 测试数量 INT, 黑水情况 NVARCHAR(200), 测试结论 NVARCHAR(20), 测试人 NVARCHAR(50), 备注 NVARCHAR(500), asp_user1 NVARCHAR(50), asp_time1 DATETIME2 DEFAULT GETDATE(), asp_cancel CHAR(1) DEFAULT 'N');
IF NOT EXISTS (SELECT 1 FROM yj_panel WHERE panel_code='PR_BLACK_TEST') INSERT INTO yj_panel (panel_code,panel_name,category,mode,line_table,head_table,group_col,pk_col,prefix,date_col,module_group) VALUES ('PR_BLACK_TEST',N'黑水测试记录',N'单据','doc','pr_black_test','pr_black_test','单据编号','id','PBT','单据日期',N'生产制造');
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='PR_BLACK_TEST' AND place='header') INSERT INTO yj_field (panel_code,col_name,label,data_type,place,seq,width,editable,required) VALUES ('PR_BLACK_TEST','单据编号',N'单据编号','文本','header',1,140,0,1),('PR_BLACK_TEST','单据日期',N'单据日期','日期','header',2,120,1,1),('PR_BLACK_TEST','工单号',N'工单号','文本','header',3,130,1,0),('PR_BLACK_TEST','炭棒批号',N'炭棒批号','文本','header',4,120,1,0),('PR_BLACK_TEST','测试数量',N'测试数量','整数','header',5,100,1,0),('PR_BLACK_TEST','黑水情况',N'黑水情况','文本','header',6,200,1,0),('PR_BLACK_TEST','测试结论',N'测试结论','下拉框','header',7,100,1,0),('PR_BLACK_TEST','测试人',N'测试人','文本','header',8,100,1,0),('PR_BLACK_TEST','备注',N'备注','文本','header',9,200,1,0);
GO
IF OBJECT_ID('pr_patrol_qc') IS NULL CREATE TABLE pr_patrol_qc (id INT IDENTITY PRIMARY KEY, 单据编号 NVARCHAR(50) NOT NULL, 单据日期 DATE, 工序 NVARCHAR(20), 检查项目 NVARCHAR(200), 标准要求 NVARCHAR(200), 检查结果 NVARCHAR(20), 巡线人 NVARCHAR(50), 巡线时间 NVARCHAR(20), 备注 NVARCHAR(500), asp_user1 NVARCHAR(50), asp_time1 DATETIME2 DEFAULT GETDATE(), asp_cancel CHAR(1) DEFAULT 'N');
IF NOT EXISTS (SELECT 1 FROM yj_panel WHERE panel_code='PR_PATROL_QC') INSERT INTO yj_panel (panel_code,panel_name,category,mode,line_table,head_table,group_col,pk_col,prefix,date_col,module_group) VALUES ('PR_PATROL_QC',N'巡线抽检记录',N'单据','doc','pr_patrol_qc','pr_patrol_qc','单据编号','id','PPQ','单据日期',N'生产制造');
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='PR_PATROL_QC' AND place='header') INSERT INTO yj_field (panel_code,col_name,label,data_type,place,seq,width,editable,required) VALUES ('PR_PATROL_QC','单据编号',N'单据编号','文本','header',1,140,0,1),('PR_PATROL_QC','单据日期',N'单据日期','日期','header',2,120,1,1),('PR_PATROL_QC','工序',N'工序','下拉框','header',3,90,1,0),('PR_PATROL_QC','检查项目',N'检查项目','文本','header',4,200,1,0),('PR_PATROL_QC','标准要求',N'标准要求','文本','header',5,200,1,0),('PR_PATROL_QC','检查结果',N'检查结果','下拉框','header',6,90,1,0),('PR_PATROL_QC','巡线人',N'巡线人','文本','header',7,100,1,0),('PR_PATROL_QC','巡线时间',N'巡线时间','文本','header',8,100,1,0),('PR_PATROL_QC','备注',N'备注','文本','header',9,200,1,0);
GO
IF OBJECT_ID('pr_asm_daily') IS NULL CREATE TABLE pr_asm_daily (id INT IDENTITY PRIMARY KEY, 单据编号 NVARCHAR(50) NOT NULL, 单据日期 DATE, 工单号 NVARCHAR(50), 班次 NVARCHAR(10), 产品名称 NVARCHAR(100), 计划数量 DECIMAL(18,2), 组装数量 DECIMAL(18,2), 合格数量 DECIMAL(18,2), 不良数量 DECIMAL(18,2), 操作工 NVARCHAR(50), 备注 NVARCHAR(500), asp_user1 NVARCHAR(50), asp_time1 DATETIME2 DEFAULT GETDATE(), asp_cancel CHAR(1) DEFAULT 'N');
IF NOT EXISTS (SELECT 1 FROM yj_panel WHERE panel_code='PR_ASM_DAILY') INSERT INTO yj_panel (panel_code,panel_name,category,mode,line_table,head_table,group_col,pk_col,prefix,date_col,module_group) VALUES ('PR_ASM_DAILY',N'组装日报表',N'单据','doc','pr_asm_daily','pr_asm_daily','单据编号','id','PAD','单据日期',N'生产制造');
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='PR_ASM_DAILY' AND place='header') INSERT INTO yj_field (panel_code,col_name,label,data_type,place,seq,width,editable,required) VALUES ('PR_ASM_DAILY','单据编号',N'单据编号','文本','header',1,140,0,1),('PR_ASM_DAILY','单据日期',N'单据日期','日期','header',2,120,1,1),('PR_ASM_DAILY','工单号',N'工单号','文本','header',3,130,1,0),('PR_ASM_DAILY','班次',N'班次','下拉框','header',4,80,1,0),('PR_ASM_DAILY','产品名称',N'产品名称','文本','header',5,160,1,0),('PR_ASM_DAILY','计划数量',N'计划数量','小数','header',6,100,1,0),('PR_ASM_DAILY','组装数量',N'组装数量','小数','header',7,100,1,0),('PR_ASM_DAILY','合格数量',N'合格数量','小数','header',8,100,1,0),('PR_ASM_DAILY','不良数量',N'不良数量','小数','header',9,100,1,0),('PR_ASM_DAILY','操作工',N'操作工','文本','header',10,100,1,0),('PR_ASM_DAILY','备注',N'备注','文本','header',11,200,1,0);
GO
-- ═══ 跨工序/设备/其他(3张) ═══
IF OBJECT_ID('pr_maintenance') IS NULL CREATE TABLE pr_maintenance (id INT IDENTITY PRIMARY KEY, 单据编号 NVARCHAR(50) NOT NULL, 单据日期 DATE, 设备名称 NVARCHAR(100), 保养项目 NVARCHAR(200), 保养周期 NVARCHAR(50), 上次保养 DATE, 下次保养 DATE, 负责人 NVARCHAR(50), 备注 NVARCHAR(500), asp_user1 NVARCHAR(50), asp_time1 DATETIME2 DEFAULT GETDATE(), asp_cancel CHAR(1) DEFAULT 'N');
IF NOT EXISTS (SELECT 1 FROM yj_panel WHERE panel_code='PR_MAINTENANCE') INSERT INTO yj_panel (panel_code,panel_name,category,mode,line_table,head_table,group_col,pk_col,prefix,date_col,module_group) VALUES ('PR_MAINTENANCE',N'预防性保养计划',N'单据','doc','pr_maintenance','pr_maintenance','单据编号','id','PMT','单据日期',N'生产制造');
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='PR_MAINTENANCE' AND place='header') INSERT INTO yj_field (panel_code,col_name,label,data_type,place,seq,width,editable,required) VALUES ('PR_MAINTENANCE','单据编号',N'单据编号','文本','header',1,140,0,1),('PR_MAINTENANCE','单据日期',N'单据日期','日期','header',2,120,1,1),('PR_MAINTENANCE','设备名称',N'设备名称','文本','header',3,150,1,0),('PR_MAINTENANCE','保养项目',N'保养项目','文本','header',4,200,1,0),('PR_MAINTENANCE','保养周期',N'保养周期','文本','header',5,100,1,0),('PR_MAINTENANCE','上次保养',N'上次保养','日期','header',6,110,1,0),('PR_MAINTENANCE','下次保养',N'下次保养','日期','header',7,110,1,0),('PR_MAINTENANCE','负责人',N'负责人','文本','header',8,100,1,0),('PR_MAINTENANCE','备注',N'备注','文本','header',9,200,1,0);
GO
IF OBJECT_ID('pr_flow_card') IS NULL CREATE TABLE pr_flow_card (id INT IDENTITY PRIMARY KEY, 单据编号 NVARCHAR(50) NOT NULL, 单据日期 DATE, 产品批次 NVARCHAR(50), 产品编码 NVARCHAR(50), 产品规格 NVARCHAR(100), 货物形态 NVARCHAR(50), 材料 NVARCHAR(200), 生产日期 DATE, 数量 INT, 负责人 NVARCHAR(50), 第几框 INT, 共几框 INT, 备注 NVARCHAR(500), asp_user1 NVARCHAR(50), asp_time1 DATETIME2 DEFAULT GETDATE(), asp_cancel CHAR(1) DEFAULT 'N');
IF NOT EXISTS (SELECT 1 FROM yj_panel WHERE panel_code='PR_FLOW_CARD') INSERT INTO yj_panel (panel_code,panel_name,category,mode,line_table,head_table,group_col,pk_col,prefix,date_col,module_group) VALUES ('PR_FLOW_CARD',N'产品流动标识卡',N'单据','doc','pr_flow_card','pr_flow_card','单据编号','id','PFC','单据日期',N'生产制造');
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='PR_FLOW_CARD' AND place='header') INSERT INTO yj_field (panel_code,col_name,label,data_type,place,seq,width,editable,required) VALUES ('PR_FLOW_CARD','单据编号',N'单据编号','文本','header',1,140,0,1),('PR_FLOW_CARD','单据日期',N'单据日期','日期','header',2,120,1,1),('PR_FLOW_CARD','产品批次',N'产品批次','文本','header',3,120,1,0),('PR_FLOW_CARD','产品编码',N'产品编码','文本','header',4,120,1,0),('PR_FLOW_CARD','产品规格',N'产品规格','文本','header',5,150,1,0),('PR_FLOW_CARD','货物形态',N'货物形态','文本','header',6,100,1,0),('PR_FLOW_CARD','材料',N'材料','文本','header',7,200,1,0),('PR_FLOW_CARD','生产日期',N'生产日期','日期','header',8,110,1,0),('PR_FLOW_CARD','数量',N'数量','整数','header',9,80,1,0),('PR_FLOW_CARD','负责人',N'负责人','文本','header',10,100,1,0),('PR_FLOW_CARD','第几框',N'第几框','整数','header',11,80,1,0),('PR_FLOW_CARD','共几框',N'共几框','整数','header',12,80,1,0),('PR_FLOW_CARD','备注',N'备注','文本','header',13,200,1,0);
GO
IF OBJECT_ID('pr_scrap') IS NULL CREATE TABLE pr_scrap (id INT IDENTITY PRIMARY KEY, 单据编号 NVARCHAR(50) NOT NULL, 单据日期 DATE, 物料/产品名称 NVARCHAR(100), 批号 NVARCHAR(50), 报废数量 DECIMAL(18,2), 报废原因 NVARCHAR(500), 仓别 NVARCHAR(20), 经办人 NVARCHAR(50), 审批人 NVARCHAR(50), 备注 NVARCHAR(500), asp_user1 NVARCHAR(50), asp_time1 DATETIME2 DEFAULT GETDATE(), asp_cancel CHAR(1) DEFAULT 'N');
IF NOT EXISTS (SELECT 1 FROM yj_panel WHERE panel_code='PR_SCRAP') INSERT INTO yj_panel (panel_code,panel_name,category,mode,line_table,head_table,group_col,pk_col,prefix,date_col,module_group) VALUES ('PR_SCRAP',N'物料产品报废单',N'单据','doc','pr_scrap','pr_scrap','单据编号','id','PSC','单据日期',N'生产制造');
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='PR_SCRAP' AND place='header') INSERT INTO yj_field (panel_code,col_name,label,data_type,place,seq,width,editable,required) VALUES ('PR_SCRAP','单据编号',N'单据编号','文本','header',1,140,0,1),('PR_SCRAP','单据日期',N'单据日期','日期','header',2,120,1,1),('PR_SCRAP','物料/产品名称',N'物料/产品名称','文本','header',3,160,1,0),('PR_SCRAP','批号',N'批号','文本','header',4,120,1,0),('PR_SCRAP','报废数量',N'报废数量','小数','header',5,100,1,0),('PR_SCRAP','报废原因',N'报废原因','文本','header',6,300,1,0),('PR_SCRAP','仓别',N'仓别','文本','header',7,80,1,0),('PR_SCRAP','经办人',N'经办人','文本','header',8,100,1,0),('PR_SCRAP','审批人',N'审批人','文本','header',9,100,1,0),('PR_SCRAP','备注',N'备注','文本','header',10,200,1,0);
GO
-- 通用下拉字典
UPDATE yj_field SET dict_sql=N'SELECT N''合格'' AS val,N''合格'' AS lbl UNION ALL SELECT N''不合格'',N''不合格''' WHERE col_name='判定' AND panel_code LIKE 'PR_%' AND data_type='下拉框';
UPDATE yj_field SET dict_sql=N'SELECT N''合格'' AS val,N''合格'' AS lbl UNION ALL SELECT N''不合格'',N''不合格''' WHERE col_name IN ('外观判定','测试结论','检查结果') AND panel_code LIKE 'PR_%';
UPDATE yj_field SET dict_sql=N'SELECT N''白班'' AS val,N''白班'' AS lbl UNION ALL SELECT N''夜班'',N''夜班''' WHERE col_name='班次' AND panel_code LIKE 'PR_%';
UPDATE yj_field SET dict_sql=N'SELECT N''混料'' AS val,N''混料'' AS lbl UNION ALL SELECT N''成型'',N''成型'' UNION ALL SELECT N''切炭'',N''切炭'' UNION ALL SELECT N''组装'',N''组装'' UNION ALL SELECT N''装箱'',N''装箱''' WHERE col_name='工序' AND panel_code LIKE 'PR_%';
GO
PRINT N'剩余 24 张工序单据面板迁移完成';
GO
