-- migrate-prod-forms.sql — 生产相关表格数字化(11面板):按真实单据字段复现,面板风格渲染(非纸面1:1)
-- 依据: 生产相关表格文件.xlsx 29份单据字段提取(视觉走查) + 用户确认"字段和逻辑复现,不复制版式"
-- 家族归组: 日报表四合一 / 投料确认二合一 / 检验记录八类合一 / 混合四次嵌套行式化 / 点检矩阵行式化
SET NOCOUNT ON;
GO

-- ══ 1. 生产日报表 DAY_REPORT(四车间合一:字段超集,车间决定用哪部分) ══
IF OBJECT_ID('day_report') IS NULL CREATE TABLE day_report (id int IDENTITY(1,1) PRIMARY KEY, [单据编号] nvarchar(60) NOT NULL, [单据日期] nvarchar(20) NULL, [车间] nvarchar(30) NULL, [出勤人数] int NULL, [填表人] nvarchar(50) NULL, [备注] nvarchar(500) NULL, [单据状态] nvarchar(10) NOT NULL DEFAULT N'草稿', [审核人] nvarchar(50) NULL, [审核时间] nvarchar(30) NULL, asp_user1 nvarchar(50) NULL, asp_time1 datetime2 NULL, asp_user2 nvarchar(50) NULL, asp_time2 datetime2 NULL, asp_cancel char(1) NULL DEFAULT 'N');
IF OBJECT_ID('day_report_detail') IS NULL CREATE TABLE day_report_detail (id int IDENTITY(1,1) PRIMARY KEY, [单据编号] nvarchar(60) NOT NULL, [姓名] nvarchar(50) NULL, [时间] nvarchar(20) NULL, [产品编码] nvarchar(100) NULL, [产品名称] nvarchar(200) NULL, [规格] nvarchar(200) NULL, [单位] nvarchar(50) NULL, [数量] decimal(18,4) NULL, [工作内容] nvarchar(500) NULL, [灌料重每支] decimal(18,4) NULL, [物料总用量] decimal(18,4) NULL, [报废] decimal(18,4) NULL, [料头料尾重量] decimal(18,4) NULL, [工序内容] nvarchar(200) NULL, [合格数量] decimal(18,4) NULL, [损失时间] nvarchar(50) NULL, [原因] nvarchar(200) NULL, [备注] nvarchar(200) NULL, asp_user1 nvarchar(50) NULL, asp_time1 datetime2 NULL, asp_user2 nvarchar(50) NULL, asp_time2 datetime2 NULL, asp_cancel char(1) NULL DEFAULT 'N');
GO
-- ══ 2. 投料确认单 FEED_CONFIRM(阻垢粉体/通用 二合一,阶段列区分溶解/合成/A/B液) ══
IF OBJECT_ID('feed_confirm') IS NULL CREATE TABLE feed_confirm (id int IDENTITY(1,1) PRIMARY KEY, [单据编号] nvarchar(60) NOT NULL, [单据日期] nvarchar(20) NULL, [物料名称] nvarchar(100) NULL, [批号] nvarchar(30) NULL, [备注] nvarchar(500) NULL, [单据状态] nvarchar(10) NOT NULL DEFAULT N'草稿', [审核人] nvarchar(50) NULL, [审核时间] nvarchar(30) NULL, asp_user1 nvarchar(50) NULL, asp_time1 datetime2 NULL, asp_user2 nvarchar(50) NULL, asp_time2 datetime2 NULL, asp_cancel char(1) NULL DEFAULT 'N');
IF OBJECT_ID('feed_confirm_detail') IS NULL CREATE TABLE feed_confirm_detail (id int IDENTITY(1,1) PRIMARY KEY, [单据编号] nvarchar(60) NOT NULL, [投料成分] nvarchar(100) NULL, [阶段] nvarchar(30) NULL, [理论数量] decimal(18,4) NULL, [实际重量] decimal(18,4) NULL, [投料人] nvarchar(50) NULL, [是否确认] nvarchar(10) NULL, [确认人] nvarchar(50) NULL, asp_user1 nvarchar(50) NULL, asp_time1 datetime2 NULL, asp_user2 nvarchar(50) NULL, asp_time2 datetime2 NULL, asp_cancel char(1) NULL DEFAULT 'N');
GO
-- ══ 3. 物料混合记录 MIX_RECORD(四次混合嵌套 → 行式化:混合次序) ══
IF OBJECT_ID('mix_record') IS NULL CREATE TABLE mix_record (id int IDENTITY(1,1) PRIMARY KEY, [单据编号] nvarchar(60) NOT NULL, [单据日期] nvarchar(20) NULL, [物料编码] nvarchar(100) NULL, [物料名称] nvarchar(200) NULL, [生产批次] nvarchar(50) NULL, [操作人] nvarchar(50) NULL, [核对人] nvarchar(50) NULL, [备注] nvarchar(500) NULL, [单据状态] nvarchar(10) NOT NULL DEFAULT N'草稿', [审核人] nvarchar(50) NULL, [审核时间] nvarchar(30) NULL, asp_user1 nvarchar(50) NULL, asp_time1 datetime2 NULL, asp_user2 nvarchar(50) NULL, asp_time2 datetime2 NULL, asp_cancel char(1) NULL DEFAULT 'N');
IF OBJECT_ID('mix_record_detail') IS NULL CREATE TABLE mix_record_detail (id int IDENTITY(1,1) PRIMARY KEY, [单据编号] nvarchar(60) NOT NULL, [混合次序] nvarchar(20) NULL, [投料时间] nvarchar(20) NULL, [物料单批次] nvarchar(50) NULL, [重量] decimal(18,4) NULL, [混合时间] decimal(18,2) NULL, asp_user1 nvarchar(50) NULL, asp_time1 datetime2 NULL, asp_user2 nvarchar(50) NULL, asp_time2 datetime2 NULL, asp_cancel char(1) NULL DEFAULT 'N');
GO
-- ══ 4. 造粒记录 GRAN_RECORD(过程参数单表) ══
IF OBJECT_ID('gran_record') IS NULL CREATE TABLE gran_record (id int IDENTITY(1,1) PRIMARY KEY, [单据编号] nvarchar(60) NOT NULL, [单据日期] nvarchar(20) NULL, [物料名称] nvarchar(100) NULL, [生产批次] nvarchar(50) NULL, [ZHP_C批次] nvarchar(50) NULL, [ZG_C批次] nvarchar(50) NULL, [活性粉] nvarchar(100) NULL, [温度] decimal(18,2) NULL, [湿度] decimal(18,2) NULL, [PE用量] decimal(18,4) NULL, [纯水用量] decimal(18,4) NULL, [捏合时间] nvarchar(20) NULL, [吹扫时间] nvarchar(20) NULL, [测试时间] nvarchar(20) NULL, [水分含量] decimal(18,2) NULL, [取样测试人] nvarchar(50) NULL, [操作员] nvarchar(50) NULL, [备注] nvarchar(500) NULL, [单据状态] nvarchar(10) NOT NULL DEFAULT N'草稿', [审核人] nvarchar(50) NULL, [审核时间] nvarchar(30) NULL, asp_user1 nvarchar(50) NULL, asp_time1 datetime2 NULL, asp_user2 nvarchar(50) NULL, asp_time2 datetime2 NULL, asp_cancel char(1) NULL DEFAULT 'N');
GO
-- ══ 5. 检验记录单 QC_RECORD(八类合一:首件/烧结制程/脱模巡检/来料检查/材料进厂/黑水测试/巡线抽检/管控点执行) ══
IF OBJECT_ID('qc_record') IS NULL CREATE TABLE qc_record (id int IDENTITY(1,1) PRIMARY KEY, [单据编号] nvarchar(60) NOT NULL, [单据日期] nvarchar(20) NULL, [检验类型] nvarchar(30) NULL, [车间] nvarchar(50) NULL, [产品编号] nvarchar(100) NULL, [规格] nvarchar(200) NULL, [抽样数量] decimal(18,4) NULL, [不良率] decimal(18,4) NULL, [检验员] nvarchar(50) NULL, [总结论] nvarchar(20) NULL, [处理方式] nvarchar(200) NULL, [备注] nvarchar(500) NULL, [单据状态] nvarchar(10) NOT NULL DEFAULT N'草稿', [审核人] nvarchar(50) NULL, [审核时间] nvarchar(30) NULL, asp_user1 nvarchar(50) NULL, asp_time1 datetime2 NULL, asp_user2 nvarchar(50) NULL, asp_time2 datetime2 NULL, asp_cancel char(1) NULL DEFAULT 'N');
IF OBJECT_ID('qc_record_detail') IS NULL CREATE TABLE qc_record_detail (id int IDENTITY(1,1) PRIMARY KEY, [单据编号] nvarchar(60) NOT NULL, [检验项目] nvarchar(200) NULL, [标准要求] nvarchar(200) NULL, [检验结果] nvarchar(20) NULL, [实测数值] decimal(18,4) NULL, [品序号] nvarchar(20) NULL, [备注] nvarchar(200) NULL, asp_user1 nvarchar(50) NULL, asp_time1 datetime2 NULL, asp_user2 nvarchar(50) NULL, asp_time2 datetime2 NULL, asp_cancel char(1) NULL DEFAULT 'N');
GO
-- ══ 6. 无黑处理登记 WH_RECORD ══
IF OBJECT_ID('wh_record') IS NULL CREATE TABLE wh_record (id int IDENTITY(1,1) PRIMARY KEY, [单据编号] nvarchar(60) NOT NULL, [单据日期] nvarchar(20) NULL, [成型日期] nvarchar(20) NULL, [产品编号] nvarchar(100) NULL, [尺寸] nvarchar(100) NULL, [加湿前重量] decimal(18,4) NULL, [加湿后重量] decimal(18,4) NULL, [无黑时间] nvarchar(30) NULL, [取样时间] nvarchar(20) NULL, [备注] nvarchar(500) NULL, [单据状态] nvarchar(10) NOT NULL DEFAULT N'草稿', [审核人] nvarchar(50) NULL, [审核时间] nvarchar(30) NULL, asp_user1 nvarchar(50) NULL, asp_time1 datetime2 NULL, asp_user2 nvarchar(50) NULL, asp_time2 datetime2 NULL, asp_cancel char(1) NULL DEFAULT 'N');
GO
-- ══ 7. 封箱确认 PACK_CONFIRM ══
IF OBJECT_ID('pack_confirm') IS NULL CREATE TABLE pack_confirm (id int IDENTITY(1,1) PRIMARY KEY, [单据编号] nvarchar(60) NOT NULL, [装箱日期] nvarchar(20) NULL, [产品编号] nvarchar(100) NULL, [装箱数量] nvarchar(100) NULL, [装箱人] nvarchar(50) NULL, [确认人] nvarchar(50) NULL, [主管签名] nvarchar(50) NULL, [备注] nvarchar(500) NULL, [单据状态] nvarchar(10) NOT NULL DEFAULT N'草稿', [审核人] nvarchar(50) NULL, [审核时间] nvarchar(30) NULL, asp_user1 nvarchar(50) NULL, asp_time1 datetime2 NULL, asp_user2 nvarchar(50) NULL, asp_time2 datetime2 NULL, asp_cancel char(1) NULL DEFAULT 'N');
GO
-- ══ 8. 设备点检记录 EQUIP_CHECK(矩阵行式化:每项目每次点检一行) ══
IF OBJECT_ID('equip_check') IS NULL CREATE TABLE equip_check (id int IDENTITY(1,1) PRIMARY KEY, [单据编号] nvarchar(60) NOT NULL, [年月] nvarchar(20) NULL, [车间] nvarchar(50) NULL, [设备名称] nvarchar(100) NULL, [点检人] nvarchar(50) NULL, [备注] nvarchar(500) NULL, [单据状态] nvarchar(10) NOT NULL DEFAULT N'草稿', [审核人] nvarchar(50) NULL, [审核时间] nvarchar(30) NULL, asp_user1 nvarchar(50) NULL, asp_time1 datetime2 NULL, asp_user2 nvarchar(50) NULL, asp_time2 datetime2 NULL, asp_cancel char(1) NULL DEFAULT 'N');
IF OBJECT_ID('equip_check_detail') IS NULL CREATE TABLE equip_check_detail (id int IDENTITY(1,1) PRIMARY KEY, [单据编号] nvarchar(60) NOT NULL, [检查内容] nvarchar(200) NULL, [点检方法] nvarchar(200) NULL, [检查标准] nvarchar(200) NULL, [点检日期] nvarchar(20) NULL, [结果] nvarchar(20) NULL, [解决措施] nvarchar(200) NULL, asp_user1 nvarchar(50) NULL, asp_time1 datetime2 NULL, asp_user2 nvarchar(50) NULL, asp_time2 datetime2 NULL, asp_cancel char(1) NULL DEFAULT 'N');
GO
-- ══ 9. 保养计划 MAINT_PLAN ══
IF OBJECT_ID('maint_plan') IS NULL CREATE TABLE maint_plan (id int IDENTITY(1,1) PRIMARY KEY, [单据编号] nvarchar(60) NOT NULL, [使用范围] nvarchar(100) NULL, [管理人] nvarchar(50) NULL, [备注] nvarchar(500) NULL, [单据状态] nvarchar(10) NOT NULL DEFAULT N'草稿', [审核人] nvarchar(50) NULL, [审核时间] nvarchar(30) NULL, asp_user1 nvarchar(50) NULL, asp_time1 datetime2 NULL, asp_user2 nvarchar(50) NULL, asp_time2 datetime2 NULL, asp_cancel char(1) NULL DEFAULT 'N');
IF OBJECT_ID('maint_plan_detail') IS NULL CREATE TABLE maint_plan_detail (id int IDENTITY(1,1) PRIMARY KEY, [单据编号] nvarchar(60) NOT NULL, [设备名称] nvarchar(100) NULL, [保养项目] nvarchar(200) NULL, [保养内容] nvarchar(500) NULL, [具体方法] nvarchar(500) NULL, [保养周期] nvarchar(50) NULL, [计划保养时间] nvarchar(50) NULL, [保养人] nvarchar(50) NULL, [保养情况] nvarchar(500) NULL, asp_user1 nvarchar(50) NULL, asp_time1 datetime2 NULL, asp_user2 nvarchar(50) NULL, asp_time2 datetime2 NULL, asp_cancel char(1) NULL DEFAULT 'N');
GO
-- ══ 10. 样品申请单 SAMPLE_REQ ══
IF OBJECT_ID('sample_req') IS NULL CREATE TABLE sample_req (id int IDENTITY(1,1) PRIMARY KEY, [单据编号] nvarchar(60) NOT NULL, [申请编码] nvarchar(30) NULL, [客户名] nvarchar(200) NULL, [费用] nvarchar(50) NULL, [下单日期] nvarchar(20) NULL, [录入人] nvarchar(50) NULL, [审核人2] nvarchar(50) NULL, [执行人] nvarchar(50) NULL, [进度描述] nvarchar(500) NULL, [备注] nvarchar(500) NULL, [单据状态] nvarchar(10) NOT NULL DEFAULT N'草稿', [审核人] nvarchar(50) NULL, [审核时间] nvarchar(30) NULL, asp_user1 nvarchar(50) NULL, asp_time1 datetime2 NULL, asp_user2 nvarchar(50) NULL, asp_time2 datetime2 NULL, asp_cancel char(1) NULL DEFAULT 'N');
IF OBJECT_ID('sample_req_detail') IS NULL CREATE TABLE sample_req_detail (id int IDENTITY(1,1) PRIMARY KEY, [单据编号] nvarchar(60) NOT NULL, [样品种类] nvarchar(100) NULL, [产品整体规格] nvarchar(200) NULL, [数量] decimal(18,4) NULL, [打样背景] nvarchar(500) NULL, [相关要求] nvarchar(500) NULL, [交期] nvarchar(20) NULL, [特殊要点] nvarchar(500) NULL, asp_user1 nvarchar(50) NULL, asp_time1 datetime2 NULL, asp_user2 nvarchar(50) NULL, asp_time2 datetime2 NULL, asp_cancel char(1) NULL DEFAULT 'N');
GO
-- ══ 11. 炭棒不良退货登记 ROD_RETURN(补时间维度——纸质表缺失,电子化改进) ══
IF OBJECT_ID('rod_return') IS NULL CREATE TABLE rod_return (id int IDENTITY(1,1) PRIMARY KEY, [单据编号] nvarchar(60) NOT NULL, [单据日期] nvarchar(20) NULL, [产品编号] nvarchar(100) NULL, [规格] nvarchar(200) NULL, [生产数量] decimal(18,4) NULL, [不良数量] decimal(18,4) NULL, [不良现象] nvarchar(500) NULL, [责任部门] nvarchar(100) NULL, [备注] nvarchar(500) NULL, [单据状态] nvarchar(10) NOT NULL DEFAULT N'草稿', [审核人] nvarchar(50) NULL, [审核时间] nvarchar(30) NULL, asp_user1 nvarchar(50) NULL, asp_time1 datetime2 NULL, asp_user2 nvarchar(50) NULL, asp_time2 datetime2 NULL, asp_cancel char(1) NULL DEFAULT 'N');
GO

-- ══ 面板注册 ══
IF NOT EXISTS (SELECT 1 FROM yj_panel WHERE panel_code='DAY_REPORT') INSERT INTO yj_panel (panel_code, panel_name, category, mode, line_table, head_table, group_col, pk_col, code_col, prefix, date_col, page_size, detail_key, module_group) VALUES ('DAY_REPORT', N'生产日报表', N'生产管理', 'doc', 'day_report_detail', 'day_report', N'单据编号', N'id', N'单据编号', N'RB', N'单据日期', 20, 'items', N'生产制造');
IF NOT EXISTS (SELECT 1 FROM yj_panel WHERE panel_code='FEED_CONFIRM') INSERT INTO yj_panel (panel_code, panel_name, category, mode, line_table, head_table, group_col, pk_col, code_col, prefix, date_col, page_size, detail_key, module_group) VALUES ('FEED_CONFIRM', N'投料确认单', N'生产管理', 'doc', 'feed_confirm_detail', 'feed_confirm', N'单据编号', N'id', N'单据编号', N'TR', N'单据日期', 20, 'items', N'生产制造');
IF NOT EXISTS (SELECT 1 FROM yj_panel WHERE panel_code='MIX_RECORD') INSERT INTO yj_panel (panel_code, panel_name, category, mode, line_table, head_table, group_col, pk_col, code_col, prefix, date_col, page_size, detail_key, module_group) VALUES ('MIX_RECORD', N'物料混合记录', N'生产管理', 'doc', 'mix_record_detail', 'mix_record', N'单据编号', N'id', N'单据编号', N'HH', N'单据日期', 20, 'items', N'生产制造');
IF NOT EXISTS (SELECT 1 FROM yj_panel WHERE panel_code='GRAN_RECORD') INSERT INTO yj_panel (panel_code, panel_name, category, mode, line_table, head_table, group_col, pk_col, code_col, prefix, date_col, page_size, detail_key, module_group) VALUES ('GRAN_RECORD', N'造粒记录', N'生产管理', 'doc', NULL, 'gran_record', N'单据编号', N'id', N'单据编号', N'LZ', N'单据日期', 20, 'items', N'生产制造');
IF NOT EXISTS (SELECT 1 FROM yj_panel WHERE panel_code='QC_RECORD') INSERT INTO yj_panel (panel_code, panel_name, category, mode, line_table, head_table, group_col, pk_col, code_col, prefix, date_col, page_size, detail_key, module_group) VALUES ('QC_RECORD', N'检验记录单', N'生产管理', 'doc', 'qc_record_detail', 'qc_record', N'单据编号', N'id', N'单据编号', N'JY', N'单据日期', 20, 'items', N'生产制造');
IF NOT EXISTS (SELECT 1 FROM yj_panel WHERE panel_code='WH_RECORD') INSERT INTO yj_panel (panel_code, panel_name, category, mode, line_table, head_table, group_col, pk_col, code_col, prefix, date_col, page_size, detail_key, module_group) VALUES ('WH_RECORD', N'无黑处理登记', N'生产管理', 'doc', NULL, 'wh_record', N'单据编号', N'id', N'单据编号', N'WB', N'单据日期', 20, 'items', N'生产制造');
IF NOT EXISTS (SELECT 1 FROM yj_panel WHERE panel_code='PACK_CONFIRM') INSERT INTO yj_panel (panel_code, panel_name, category, mode, line_table, head_table, group_col, pk_col, code_col, prefix, date_col, page_size, detail_key, module_group) VALUES ('PACK_CONFIRM', N'封箱确认', N'生产管理', 'doc', NULL, 'pack_confirm', N'单据编号', N'id', N'单据编号', N'FX', N'装箱日期', 20, 'items', N'生产制造');
IF NOT EXISTS (SELECT 1 FROM yj_panel WHERE panel_code='EQUIP_CHECK') INSERT INTO yj_panel (panel_code, panel_name, category, mode, line_table, head_table, group_col, pk_col, code_col, prefix, date_col, page_size, detail_key, module_group) VALUES ('EQUIP_CHECK', N'设备点检记录', N'生产管理', 'doc', 'equip_check_detail', 'equip_check', N'单据编号', N'id', N'单据编号', N'DJ', N'年月', 20, 'items', N'生产制造');
IF NOT EXISTS (SELECT 1 FROM yj_panel WHERE panel_code='MAINT_PLAN') INSERT INTO yj_panel (panel_code, panel_name, category, mode, line_table, head_table, group_col, pk_col, code_col, prefix, date_col, page_size, detail_key, module_group) VALUES ('MAINT_PLAN', N'保养计划', N'生产管理', 'doc', 'maint_plan_detail', 'maint_plan', N'单据编号', N'id', N'单据编号', N'BY', NULL, 20, 'items', N'生产制造');
IF NOT EXISTS (SELECT 1 FROM yj_panel WHERE panel_code='SAMPLE_REQ') INSERT INTO yj_panel (panel_code, panel_name, category, mode, line_table, head_table, group_col, pk_col, code_col, prefix, date_col, page_size, detail_key, module_group) VALUES ('SAMPLE_REQ', N'样品申请单', N'生产管理', 'doc', 'sample_req_detail', 'sample_req', N'单据编号', N'id', N'单据编号', N'SP', N'下单日期', 20, 'items', N'生产制造');
IF NOT EXISTS (SELECT 1 FROM yj_panel WHERE panel_code='ROD_RETURN') INSERT INTO yj_panel (panel_code, panel_name, category, mode, line_table, head_table, group_col, pk_col, code_col, prefix, date_col, page_size, detail_key, module_group) VALUES ('ROD_RETURN', N'炭棒不良退货登记', N'生产管理', 'doc', NULL, 'rod_return', N'单据编号', N'id', N'单据编号', N'TL', N'单据日期', 20, 'items', N'生产制造');
GO
PRINT N'migrate-prod-forms 完成:11面板+表结构';
GO
