-- migrate-prod-forms-fields3.sql — 11面板字段(3/3:无黑/封箱/点检/保养/样品/退料 + 修正 + 译名)
SET NOCOUNT ON;
GO
-- 修正:QC_RECORD 备注共享头行(同 QC_RECV 模式),去掉误加的 备注2
DELETE FROM yj_field WHERE panel_code='QC_RECORD' AND col_name=N'备注2';
UPDATE yj_field SET place = N'header,detail' WHERE panel_code='QC_RECORD' AND col_name=N'备注';
GO
-- ══ WH_RECORD 无黑处理登记 ══
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='WH_RECORD' AND col_name=N'单据编号') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('WH_RECORD', N'单据编号', N'单据编号', N'文本', NULL, NULL, NULL, NULL, N'query,header', 10, 140, 0, 1, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='WH_RECORD' AND col_name=N'单据日期') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('WH_RECORD', N'单据日期', N'单据日期', N'日期', NULL, NULL, NULL, NULL, N'query,header', 20, 120, 1, 1, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='WH_RECORD' AND col_name=N'成型日期') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('WH_RECORD', N'成型日期', N'成型日期', N'文本', NULL, NULL, NULL, NULL, N'header', 30, 110, 1, 0, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='WH_RECORD' AND col_name=N'产品编号') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('WH_RECORD', N'产品编号', N'产品编号', N'文本', NULL, NULL, NULL, NULL, N'query,header', 40, 110, 1, 1, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='WH_RECORD' AND col_name=N'尺寸') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('WH_RECORD', N'尺寸', N'尺寸', N'文本', NULL, NULL, NULL, NULL, N'header', 50, 100, 1, 0, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='WH_RECORD' AND col_name=N'加湿前重量') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('WH_RECORD', N'加湿前重量', N'加湿前重量', N'小数', NULL, NULL, NULL, NULL, N'header', 60, 100, 1, 0, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='WH_RECORD' AND col_name=N'加湿后重量') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('WH_RECORD', N'加湿后重量', N'加湿后重量', N'小数', NULL, NULL, NULL, NULL, N'header', 70, 100, 1, 0, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='WH_RECORD' AND col_name=N'无黑时间') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('WH_RECORD', N'无黑时间', N'无黑时间', N'文本', NULL, NULL, NULL, NULL, N'header', 80, 100, 1, 0, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='WH_RECORD' AND col_name=N'取样时间') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('WH_RECORD', N'取样时间', N'取样时间', N'文本', NULL, NULL, NULL, NULL, N'header', 90, 100, 1, 0, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='WH_RECORD' AND col_name=N'备注') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('WH_RECORD', N'备注', N'备注', N'文本', NULL, NULL, NULL, NULL, N'header', 100, 200, 1, 0, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='WH_RECORD' AND col_name=N'单据状态') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('WH_RECORD', N'单据状态', N'单据状态', N'文本', NULL, NULL, NULL, NULL, N'query,header', 110, 90, 0, 0, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='WH_RECORD' AND col_name=N'审核人') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('WH_RECORD', N'审核人', N'审核人', N'文本', NULL, NULL, NULL, NULL, N'header', 120, 90, 0, 0, 0, 1);
GO
-- ══ PACK_CONFIRM 封箱确认 ══
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='PACK_CONFIRM' AND col_name=N'单据编号') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('PACK_CONFIRM', N'单据编号', N'单据编号', N'文本', NULL, NULL, NULL, NULL, N'query,header', 10, 140, 0, 1, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='PACK_CONFIRM' AND col_name=N'装箱日期') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('PACK_CONFIRM', N'装箱日期', N'装箱日期', N'日期', NULL, NULL, NULL, NULL, N'query,header', 20, 120, 1, 1, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='PACK_CONFIRM' AND col_name=N'产品编号') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('PACK_CONFIRM', N'产品编号', N'产品编号', N'文本', NULL, NULL, NULL, NULL, N'query,header', 30, 120, 1, 1, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='PACK_CONFIRM' AND col_name=N'装箱数量') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('PACK_CONFIRM', N'装箱数量', N'装箱数量', N'文本', NULL, NULL, NULL, NULL, N'header', 40, 140, 1, 1, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='PACK_CONFIRM' AND col_name=N'装箱人') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('PACK_CONFIRM', N'装箱人', N'装箱人', N'文本', NULL, NULL, NULL, NULL, N'header', 50, 90, 1, 0, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='PACK_CONFIRM' AND col_name=N'确认人') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('PACK_CONFIRM', N'确认人', N'确认人', N'文本', NULL, NULL, NULL, NULL, N'header', 60, 90, 1, 0, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='PACK_CONFIRM' AND col_name=N'主管签名') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('PACK_CONFIRM', N'主管签名', N'主管签名', N'文本', NULL, NULL, NULL, NULL, N'header', 70, 100, 1, 0, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='PACK_CONFIRM' AND col_name=N'备注') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('PACK_CONFIRM', N'备注', N'备注', N'文本', NULL, NULL, NULL, NULL, N'header', 80, 200, 1, 0, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='PACK_CONFIRM' AND col_name=N'单据状态') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('PACK_CONFIRM', N'单据状态', N'单据状态', N'文本', NULL, NULL, NULL, NULL, N'query,header', 90, 90, 0, 0, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='PACK_CONFIRM' AND col_name=N'审核人') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('PACK_CONFIRM', N'审核人', N'审核人', N'文本', NULL, NULL, NULL, NULL, N'header', 100, 90, 0, 0, 0, 1);
GO
-- ══ EQUIP_CHECK 设备点检记录 ══
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='EQUIP_CHECK' AND col_name=N'单据编号') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('EQUIP_CHECK', N'单据编号', N'单据编号', N'文本', NULL, NULL, NULL, NULL, N'query,header', 10, 140, 0, 1, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='EQUIP_CHECK' AND col_name=N'年月') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('EQUIP_CHECK', N'年月', N'年月', N'文本', NULL, NULL, NULL, NULL, N'query,header', 20, 90, 1, 1, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='EQUIP_CHECK' AND col_name=N'车间') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('EQUIP_CHECK', N'车间', N'车间', N'文本', NULL, NULL, NULL, NULL, N'query,header', 30, 110, 1, 0, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='EQUIP_CHECK' AND col_name=N'设备名称') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('EQUIP_CHECK', N'设备名称', N'设备名称', N'参照', NULL, N'EQUIP', N'设备名称', N'设备名称', N'query,header', 40, 130, 1, 1, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='EQUIP_CHECK' AND col_name=N'点检人') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('EQUIP_CHECK', N'点检人', N'点检人', N'文本', NULL, NULL, NULL, NULL, N'header', 50, 90, 1, 0, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='EQUIP_CHECK' AND col_name=N'备注') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('EQUIP_CHECK', N'备注', N'备注', N'文本', NULL, NULL, NULL, NULL, N'header,detail', 60, 200, 1, 0, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='EQUIP_CHECK' AND col_name=N'单据状态') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('EQUIP_CHECK', N'单据状态', N'单据状态', N'文本', NULL, NULL, NULL, NULL, N'query,header', 70, 90, 0, 0, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='EQUIP_CHECK' AND col_name=N'检查内容') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('EQUIP_CHECK', N'检查内容', N'检查内容', N'文本', NULL, NULL, NULL, NULL, N'query,detail', 200, 180, 1, 1, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='EQUIP_CHECK' AND col_name=N'点检方法') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('EQUIP_CHECK', N'点检方法', N'点检方法及工具', N'文本', NULL, NULL, NULL, NULL, N'detail', 210, 160, 1, 0, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='EQUIP_CHECK' AND col_name=N'检查标准') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('EQUIP_CHECK', N'检查标准', N'检查标准', N'文本', NULL, NULL, NULL, NULL, N'detail', 220, 160, 1, 0, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='EQUIP_CHECK' AND col_name=N'点检日期') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('EQUIP_CHECK', N'点检日期', N'点检日期', N'文本', NULL, NULL, NULL, NULL, N'query,detail', 230, 100, 1, 0, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='EQUIP_CHECK' AND col_name=N'结果') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('EQUIP_CHECK', N'结果', N'结果', N'下拉框', N'SELECT v FROM (VALUES (N''正常''),(N''异常'')) AS t(v)', NULL, NULL, NULL, N'query,detail', 240, 80, 1, 0, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='EQUIP_CHECK' AND col_name=N'解决措施') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('EQUIP_CHECK', N'解决措施', N'解决措施', N'文本', NULL, NULL, NULL, NULL, N'detail', 250, 180, 1, 0, 0, 1);
GO
PRINT N'fields 3/3a 完成';
GO
