-- migrate-prod-forms-fields2.sql — 11面板字段(2/3:造粒/检验/无黑/封箱/点检/保养/样品/退料)
SET NOCOUNT ON;
GO
-- ══ GRAN_RECORD 造粒记录(单表式:全头字段) ══
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='GRAN_RECORD' AND col_name=N'单据编号') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('GRAN_RECORD', N'单据编号', N'单据编号', N'文本', NULL, NULL, NULL, NULL, N'query,header', 10, 140, 0, 1, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='GRAN_RECORD' AND col_name=N'单据日期') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('GRAN_RECORD', N'单据日期', N'单据日期', N'日期', NULL, NULL, NULL, NULL, N'query,header', 20, 120, 1, 1, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='GRAN_RECORD' AND col_name=N'物料名称') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('GRAN_RECORD', N'物料名称', N'物料名称', N'文本', NULL, NULL, NULL, NULL, N'query,header', 30, 140, 1, 1, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='GRAN_RECORD' AND col_name=N'生产批次') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('GRAN_RECORD', N'生产批次', N'生产批次', N'文本', NULL, NULL, NULL, NULL, N'query,header', 40, 110, 1, 0, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='GRAN_RECORD' AND col_name=N'ZHP_C批次') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('GRAN_RECORD', N'ZHP_C批次', N'Z-HP-C批次', N'文本', NULL, NULL, NULL, NULL, N'header', 50, 110, 1, 0, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='GRAN_RECORD' AND col_name=N'ZG_C批次') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('GRAN_RECORD', N'ZG_C批次', N'Z-G-C批次', N'文本', NULL, NULL, NULL, NULL, N'header', 60, 110, 1, 0, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='GRAN_RECORD' AND col_name=N'活性粉') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('GRAN_RECORD', N'活性粉', N'活性粉', N'文本', NULL, NULL, NULL, NULL, N'header', 70, 110, 1, 0, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='GRAN_RECORD' AND col_name=N'温度') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('GRAN_RECORD', N'温度', N'温度/℃', N'小数', NULL, NULL, NULL, NULL, N'header', 80, 80, 1, 0, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='GRAN_RECORD' AND col_name=N'湿度') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('GRAN_RECORD', N'湿度', N'湿度/%', N'小数', NULL, NULL, NULL, NULL, N'header', 90, 80, 1, 0, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='GRAN_RECORD' AND col_name=N'PE用量') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('GRAN_RECORD', N'PE用量', N'P-E/kg', N'小数', NULL, NULL, NULL, NULL, N'header', 100, 80, 1, 0, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='GRAN_RECORD' AND col_name=N'纯水用量') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('GRAN_RECORD', N'纯水用量', N'纯水/kg', N'小数', NULL, NULL, NULL, NULL, N'header', 110, 80, 1, 0, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='GRAN_RECORD' AND col_name=N'捏合时间') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('GRAN_RECORD', N'捏合时间', N'捏合时间', N'文本', NULL, NULL, NULL, NULL, N'header', 120, 90, 1, 0, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='GRAN_RECORD' AND col_name=N'吹扫时间') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('GRAN_RECORD', N'吹扫时间', N'吹扫时间', N'文本', NULL, NULL, NULL, NULL, N'header', 130, 90, 1, 0, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='GRAN_RECORD' AND col_name=N'测试时间') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('GRAN_RECORD', N'测试时间', N'测试时间', N'文本', NULL, NULL, NULL, NULL, N'header', 140, 90, 1, 0, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='GRAN_RECORD' AND col_name=N'水分含量') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('GRAN_RECORD', N'水分含量', N'水分含量/%', N'小数', NULL, NULL, NULL, NULL, N'query,header', 150, 95, 1, 0, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='GRAN_RECORD' AND col_name=N'取样测试人') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('GRAN_RECORD', N'取样测试人', N'取样测试人', N'文本', NULL, NULL, NULL, NULL, N'header', 160, 100, 1, 0, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='GRAN_RECORD' AND col_name=N'操作员') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('GRAN_RECORD', N'操作员', N'操作员', N'文本', NULL, NULL, NULL, NULL, N'header', 170, 90, 1, 0, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='GRAN_RECORD' AND col_name=N'备注') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('GRAN_RECORD', N'备注', N'备注', N'文本', NULL, NULL, NULL, NULL, N'header', 180, 200, 1, 0, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='GRAN_RECORD' AND col_name=N'单据状态') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('GRAN_RECORD', N'单据状态', N'单据状态', N'文本', NULL, NULL, NULL, NULL, N'query,header', 190, 90, 0, 0, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='GRAN_RECORD' AND col_name=N'审核人') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('GRAN_RECORD', N'审核人', N'审核人', N'文本', NULL, NULL, NULL, NULL, N'header', 200, 90, 0, 0, 0, 1);
GO
-- ══ QC_RECORD 检验记录单(八类合一) ══
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='QC_RECORD' AND col_name=N'单据编号') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('QC_RECORD', N'单据编号', N'单据编号', N'文本', NULL, NULL, NULL, NULL, N'query,header', 10, 140, 0, 1, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='QC_RECORD' AND col_name=N'单据日期') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('QC_RECORD', N'单据日期', N'单据日期', N'日期', NULL, NULL, NULL, NULL, N'query,header', 20, 120, 1, 1, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='QC_RECORD' AND col_name=N'检验类型') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('QC_RECORD', N'检验类型', N'检验类型', N'下拉框', N'SELECT v FROM (VALUES (N''首件检验''),(N''烧结制程巡检''),(N''脱模巡检''),(N''来料检查(组装)''),(N''材料进厂检查''),(N''黑水测试''),(N''巡线抽检''),(N''管控点检查'')) AS t(v)', NULL, NULL, NULL, N'query,header', 30, 130, 1, 1, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='QC_RECORD' AND col_name=N'车间') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('QC_RECORD', N'车间', N'车间', N'文本', NULL, NULL, NULL, NULL, N'query,header', 40, 110, 1, 0, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='QC_RECORD' AND col_name=N'产品编号') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('QC_RECORD', N'产品编号', N'产品编号', N'文本', NULL, NULL, NULL, NULL, N'query,header', 50, 110, 1, 0, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='QC_RECORD' AND col_name=N'规格') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('QC_RECORD', N'规格', N'规格', N'文本', NULL, NULL, NULL, NULL, N'header', 60, 110, 1, 0, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='QC_RECORD' AND col_name=N'抽样数量') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('QC_RECORD', N'抽样数量', N'抽样数量', N'小数', NULL, NULL, NULL, NULL, N'header', 70, 90, 1, 0, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='QC_RECORD' AND col_name=N'不良率') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('QC_RECORD', N'不良率', N'不良率%(>3%不合格)', N'小数', NULL, NULL, NULL, NULL, N'query,header', 80, 130, 1, 0, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='QC_RECORD' AND col_name=N'检验员') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('QC_RECORD', N'检验员', N'检验员', N'文本', NULL, NULL, NULL, NULL, N'query,header', 90, 90, 1, 0, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='QC_RECORD' AND col_name=N'总结论') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('QC_RECORD', N'总结论', N'总结论', N'下拉框', N'SELECT v FROM (VALUES (N''合格''),(N''不合格''),(N''让步接收'')) AS t(v)', NULL, NULL, NULL, N'query,header', 100, 100, 1, 0, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='QC_RECORD' AND col_name=N'处理方式') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('QC_RECORD', N'处理方式', N'处理方式', N'文本', NULL, NULL, NULL, NULL, N'header', 110, 180, 1, 0, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='QC_RECORD' AND col_name=N'备注') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('QC_RECORD', N'备注', N'备注', N'文本', NULL, NULL, NULL, NULL, N'header,detail', 120, 180, 1, 0, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='QC_RECORD' AND col_name=N'单据状态') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('QC_RECORD', N'单据状态', N'单据状态', N'文本', NULL, NULL, NULL, NULL, N'query,header', 130, 90, 0, 0, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='QC_RECORD' AND col_name=N'审核人') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('QC_RECORD', N'审核人', N'审核人', N'文本', NULL, NULL, NULL, NULL, N'header', 140, 90, 0, 0, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='QC_RECORD' AND col_name=N'检验项目') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('QC_RECORD', N'检验项目', N'检验项目', N'文本', NULL, NULL, NULL, NULL, N'query,detail', 200, 180, 1, 1, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='QC_RECORD' AND col_name=N'标准要求') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('QC_RECORD', N'标准要求', N'标准要求', N'文本', NULL, NULL, NULL, NULL, N'detail', 210, 160, 1, 0, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='QC_RECORD' AND col_name=N'检验结果') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('QC_RECORD', N'检验结果', N'检验结果', N'下拉框', N'SELECT v FROM (VALUES (N''合格''),(N''不合格'')) AS t(v)', NULL, NULL, NULL, N'query,detail', 220, 90, 1, 0, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='QC_RECORD' AND col_name=N'实测数值') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('QC_RECORD', N'实测数值', N'实测数值', N'小数', NULL, NULL, NULL, NULL, N'detail', 230, 95, 1, 0, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='QC_RECORD' AND col_name=N'品序号') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('QC_RECORD', N'品序号', N'品序号(首件1#/2#…)', N'文本', NULL, NULL, NULL, NULL, N'detail', 240, 120, 1, 0, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='QC_RECORD' AND col_name=N'备注2') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('QC_RECORD', N'备注2', N'备注', N'文本', NULL, NULL, NULL, NULL, N'detail', 250, 160, 1, 0, 0, 1);
GO
PRINT N'fields 2/3 完成';
GO
