-- migrate-prod-forms-fields.sql — 11面板的 yj_field + 译名(承接 migrate-prod-forms.sql)
SET NOCOUNT ON;
GO
-- 通用小工具:字段插入模板已展开为字面量(保持仓库风格)

-- ══ DAY_REPORT 生产日报表 ══
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='DAY_REPORT' AND col_name=N'单据编号') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('DAY_REPORT', N'单据编号', N'单据编号', N'文本', NULL, NULL, NULL, NULL, N'query,header', 10, 140, 0, 1, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='DAY_REPORT' AND col_name=N'单据日期') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('DAY_REPORT', N'单据日期', N'单据日期', N'日期', NULL, NULL, NULL, NULL, N'query,header', 20, 120, 1, 1, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='DAY_REPORT' AND col_name=N'车间') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('DAY_REPORT', N'车间', N'车间', N'下拉框', N'SELECT v FROM (VALUES (N''自制物料车间''),(N''成型车间''),(N''切炭车间''),(N''组装车间''),(N''装箱车间'')) AS t(v)', NULL, NULL, NULL, N'query,header', 30, 120, 1, 1, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='DAY_REPORT' AND col_name=N'出勤人数') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('DAY_REPORT', N'出勤人数', N'出勤人数', N'整数', NULL, NULL, NULL, NULL, N'header', 40, 90, 1, 0, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='DAY_REPORT' AND col_name=N'填表人') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('DAY_REPORT', N'填表人', N'填表人', N'文本', NULL, NULL, NULL, NULL, N'header', 50, 90, 1, 0, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='DAY_REPORT' AND col_name=N'备注') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('DAY_REPORT', N'备注', N'备注', N'文本', NULL, NULL, NULL, NULL, N'header', 60, 220, 1, 0, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='DAY_REPORT' AND col_name=N'单据状态') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('DAY_REPORT', N'单据状态', N'单据状态', N'文本', NULL, NULL, NULL, NULL, N'query,header', 70, 90, 0, 0, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='DAY_REPORT' AND col_name=N'审核人') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('DAY_REPORT', N'审核人', N'审核人', N'文本', NULL, NULL, NULL, NULL, N'header', 80, 90, 0, 0, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='DAY_REPORT' AND col_name=N'审核时间') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('DAY_REPORT', N'审核时间', N'审核时间', N'文本', NULL, NULL, NULL, NULL, N'header', 90, 140, 0, 0, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='DAY_REPORT' AND col_name=N'姓名') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('DAY_REPORT', N'姓名', N'姓名', N'文本', NULL, NULL, NULL, NULL, N'query,detail', 200, 90, 1, 1, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='DAY_REPORT' AND col_name=N'时间') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('DAY_REPORT', N'时间', N'时间', N'文本', NULL, NULL, NULL, NULL, N'detail', 210, 100, 1, 0, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='DAY_REPORT' AND col_name=N'产品编码') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('DAY_REPORT', N'产品编码', N'产品编码', N'文本', NULL, NULL, NULL, NULL, N'query,detail', 220, 110, 1, 0, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='DAY_REPORT' AND col_name=N'产品名称') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('DAY_REPORT', N'产品名称', N'产品名称', N'文本', NULL, NULL, NULL, NULL, N'detail', 230, 140, 1, 0, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='DAY_REPORT' AND col_name=N'规格') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('DAY_REPORT', N'规格', N'规格', N'文本', NULL, NULL, NULL, NULL, N'detail', 240, 110, 1, 0, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='DAY_REPORT' AND col_name=N'单位') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('DAY_REPORT', N'单位', N'单位', N'文本', NULL, NULL, NULL, NULL, N'detail', 250, 60, 1, 0, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='DAY_REPORT' AND col_name=N'数量') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('DAY_REPORT', N'数量', N'数量', N'小数', NULL, NULL, NULL, NULL, N'query,detail', 260, 90, 1, 0, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='DAY_REPORT' AND col_name=N'工作内容') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('DAY_REPORT', N'工作内容', N'工作内容', N'文本', NULL, NULL, NULL, NULL, N'detail', 270, 200, 1, 0, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='DAY_REPORT' AND col_name=N'灌料重每支') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('DAY_REPORT', N'灌料重每支', N'灌料重/支', N'小数', NULL, NULL, NULL, NULL, N'detail', 280, 95, 1, 0, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='DAY_REPORT' AND col_name=N'物料总用量') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('DAY_REPORT', N'物料总用量', N'物料总用量', N'小数', NULL, NULL, NULL, NULL, N'detail', 290, 95, 1, 0, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='DAY_REPORT' AND col_name=N'报废') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('DAY_REPORT', N'报废', N'报废', N'小数', NULL, NULL, NULL, NULL, N'detail', 300, 80, 1, 0, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='DAY_REPORT' AND col_name=N'料头料尾重量') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('DAY_REPORT', N'料头料尾重量', N'料头料尾重量', N'小数', NULL, NULL, NULL, NULL, N'detail', 310, 100, 1, 0, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='DAY_REPORT' AND col_name=N'工序内容') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('DAY_REPORT', N'工序内容', N'工序内容(组装)', N'文本', NULL, NULL, NULL, NULL, N'detail', 320, 200, 1, 0, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='DAY_REPORT' AND col_name=N'合格数量') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('DAY_REPORT', N'合格数量', N'合格数量', N'小数', NULL, NULL, NULL, NULL, N'query,detail', 330, 95, 1, 0, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='DAY_REPORT' AND col_name=N'损失时间') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('DAY_REPORT', N'损失时间', N'损失时间', N'文本', NULL, NULL, NULL, NULL, N'detail', 340, 90, 1, 0, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='DAY_REPORT' AND col_name=N'原因') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('DAY_REPORT', N'原因', N'原因', N'文本', NULL, NULL, NULL, NULL, N'detail', 350, 160, 1, 0, 0, 1);
GO

-- ══ FEED_CONFIRM 投料确认单 ══
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='FEED_CONFIRM' AND col_name=N'单据编号') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('FEED_CONFIRM', N'单据编号', N'单据编号', N'文本', NULL, NULL, NULL, NULL, N'query,header', 10, 140, 0, 1, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='FEED_CONFIRM' AND col_name=N'单据日期') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('FEED_CONFIRM', N'单据日期', N'单据日期', N'日期', NULL, NULL, NULL, NULL, N'query,header', 20, 120, 1, 1, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='FEED_CONFIRM' AND col_name=N'物料名称') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('FEED_CONFIRM', N'物料名称', N'物料名称', N'文本', NULL, NULL, NULL, NULL, N'query,header', 30, 160, 1, 1, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='FEED_CONFIRM' AND col_name=N'批号') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('FEED_CONFIRM', N'批号', N'批号', N'文本', NULL, NULL, NULL, NULL, N'query,header', 40, 120, 1, 0, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='FEED_CONFIRM' AND col_name=N'备注') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('FEED_CONFIRM', N'备注', N'备注', N'文本', NULL, NULL, NULL, NULL, N'header', 50, 220, 1, 0, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='FEED_CONFIRM' AND col_name=N'单据状态') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('FEED_CONFIRM', N'单据状态', N'单据状态', N'文本', NULL, NULL, NULL, NULL, N'query,header', 60, 90, 0, 0, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='FEED_CONFIRM' AND col_name=N'审核人') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('FEED_CONFIRM', N'审核人', N'审核人', N'文本', NULL, NULL, NULL, NULL, N'header', 70, 90, 0, 0, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='FEED_CONFIRM' AND col_name=N'投料成分') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('FEED_CONFIRM', N'投料成分', N'投料成分', N'文本', NULL, NULL, NULL, NULL, N'query,detail', 200, 130, 1, 1, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='FEED_CONFIRM' AND col_name=N'阶段') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('FEED_CONFIRM', N'阶段', N'阶段', N'下拉框', N'SELECT v FROM (VALUES (N''溶解''),(N''合成''),(N''A液''),(N''B液''),(N''浆体'')) AS t(v)', NULL, NULL, NULL, N'detail', 210, 90, 1, 0, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='FEED_CONFIRM' AND col_name=N'理论数量') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('FEED_CONFIRM', N'理论数量', N'理论数量/kg', N'小数', NULL, NULL, NULL, NULL, N'detail', 220, 100, 1, 0, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='FEED_CONFIRM' AND col_name=N'实际重量') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('FEED_CONFIRM', N'实际重量', N'最终投料重量/kg', N'小数', NULL, NULL, NULL, NULL, N'detail', 230, 110, 1, 1, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='FEED_CONFIRM' AND col_name=N'投料人') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('FEED_CONFIRM', N'投料人', N'投料人', N'文本', NULL, NULL, NULL, NULL, N'detail', 240, 90, 1, 0, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='FEED_CONFIRM' AND col_name=N'是否确认') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('FEED_CONFIRM', N'是否确认', N'是否确认', N'是否', NULL, NULL, NULL, NULL, N'detail', 250, 80, 1, 0, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='FEED_CONFIRM' AND col_name=N'确认人') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('FEED_CONFIRM', N'确认人', N'确认人', N'文本', NULL, NULL, NULL, NULL, N'detail', 260, 90, 1, 0, 0, 1);
GO

-- ══ MIX_RECORD 物料混合记录 ══
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='MIX_RECORD' AND col_name=N'单据编号') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('MIX_RECORD', N'单据编号', N'单据编号', N'文本', NULL, NULL, NULL, NULL, N'query,header', 10, 140, 0, 1, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='MIX_RECORD' AND col_name=N'单据日期') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('MIX_RECORD', N'单据日期', N'单据日期', N'日期', NULL, NULL, NULL, NULL, N'query,header', 20, 120, 1, 1, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='MIX_RECORD' AND col_name=N'物料编码') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('MIX_RECORD', N'物料编码', N'物料编码', N'文本', NULL, NULL, NULL, NULL, N'query,header', 30, 120, 1, 1, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='MIX_RECORD' AND col_name=N'物料名称') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('MIX_RECORD', N'物料名称', N'物料名称', N'文本', NULL, NULL, NULL, NULL, N'header', 40, 150, 1, 0, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='MIX_RECORD' AND col_name=N'生产批次') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('MIX_RECORD', N'生产批次', N'生产批次', N'文本', NULL, NULL, NULL, NULL, N'query,header', 50, 120, 1, 0, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='MIX_RECORD' AND col_name=N'操作人') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('MIX_RECORD', N'操作人', N'操作人', N'文本', NULL, NULL, NULL, NULL, N'header', 60, 90, 1, 0, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='MIX_RECORD' AND col_name=N'核对人') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('MIX_RECORD', N'核对人', N'核对人', N'文本', NULL, NULL, NULL, NULL, N'header', 70, 90, 1, 0, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='MIX_RECORD' AND col_name=N'备注') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('MIX_RECORD', N'备注', N'备注', N'文本', NULL, NULL, NULL, NULL, N'header', 80, 220, 1, 0, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='MIX_RECORD' AND col_name=N'单据状态') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('MIX_RECORD', N'单据状态', N'单据状态', N'文本', NULL, NULL, NULL, NULL, N'query,header', 90, 90, 0, 0, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='MIX_RECORD' AND col_name=N'混合次序') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('MIX_RECORD', N'混合次序', N'混合次序', N'下拉框', N'SELECT v FROM (VALUES (N''第一次''),(N''第二次''),(N''第三次''),(N''第四次'')) AS t(v)', NULL, NULL, NULL, N'query,detail', 200, 90, 1, 1, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='MIX_RECORD' AND col_name=N'投料时间') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('MIX_RECORD', N'投料时间', N'投料时间', N'文本', NULL, NULL, NULL, NULL, N'detail', 210, 110, 1, 0, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='MIX_RECORD' AND col_name=N'物料单批次') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('MIX_RECORD', N'物料单批次', N'物料单批次', N'文本', NULL, NULL, NULL, NULL, N'detail', 220, 120, 1, 0, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='MIX_RECORD' AND col_name=N'重量') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('MIX_RECORD', N'重量', N'重量/kg', N'小数', NULL, NULL, NULL, NULL, N'detail', 230, 90, 1, 1, 0, 1);
IF NOT EXISTS (SELECT 1 FROM yj_field WHERE panel_code='MIX_RECORD' AND col_name=N'混合时间') INSERT INTO yj_field (panel_code, col_name, label, data_type, dict_sql, ref_panel, ref_field, display_field, place, seq, width, editable, required, hidden, visible) VALUES ('MIX_RECORD', N'混合时间', N'混合时间/min', N'小数', NULL, NULL, NULL, NULL, N'detail', 240, 100, 1, 0, 0, 1);
GO
PRINT N'migrate-prod-forms-fields 完成(1/3:日报/投料/混合)';
GO
